'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace LightSwitchApplication.Implementation
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class ApplicationDataDataService
        Inherits Global.Microsoft.LightSwitch.ServerGenerated.Implementation.DataService(Of Global.LightSwitchApplication.Implementation.ApplicationData)
    
        Public Sub New()
            MyBase.New()
        End Sub
    
        Protected Overrides Function GetDataService(dataWorkspace As Global.Microsoft.LightSwitch.IDataWorkspace) As Global.Microsoft.LightSwitch.IDataService
            Return DirectCast(dataWorkspace, Global.LightSwitchApplication.DataWorkspace).ApplicationData
        End Function
    
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class ApplicationDataServiceImplementation
        Inherits Global.Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation(Of Global.LightSwitchApplication.Implementation.ApplicationData)
    
        Public Sub New(ByVal dataService As Global.Microsoft.LightSwitch.IDataService)
            MyBase.New(dataService)
        End Sub
    
    #Region "Queries"
    #End Region

    #Region "Protected methods"
        Protected Overrides Function CreateObject(ByVal type As Global.System.Type) As Object
            If (GetType(Global.LightSwitchApplication.Implementation.AVANCEDEOBRA).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.AVANCEDEOBRA
            End If
            If (GetType(Global.LightSwitchApplication.Implementation.CONSTRUCCIONDEOBRA).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.CONSTRUCCIONDEOBRA
            End If
            If (GetType(Global.LightSwitchApplication.Implementation.INSPECCIONMUNICIPAL).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.INSPECCIONMUNICIPAL
            End If
            If (GetType(Global.LightSwitchApplication.Implementation.INSPECCION).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.INSPECCION
            End If
            If (GetType(Global.LightSwitchApplication.Implementation.OBRA).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.OBRA
            End If
            If (GetType(Global.LightSwitchApplication.Implementation.PERMISOS).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.PERMISOS
            End If
            If (GetType(Global.LightSwitchApplication.Implementation.PLANO).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.PLANO
            End If
    
            Return MyBase.CreateObject(type)
        End Function
    
        Protected Overrides Function CreateObjectContext() As Global.LightSwitchApplication.Implementation.ApplicationData
            Dim assemblyName As String = Global.System.Reflection.Assembly.GetExecutingAssembly().GetName().Name
            Return New Global.LightSwitchApplication.Implementation.ApplicationData(Me.GetEntityConnectionString( _
                "_IntrinsicData", _
                "res://" + assemblyName + "/ApplicationData.csdl|res://" + assemblyName + "/ApplicationData.ssdl|res://" + assemblyName + "/ApplicationData.msl", _
                "System.Data.SqlClient", _
                True))
        End Function
    
        Protected Overrides Function CreateEntityImplementation(Of T As Global.Microsoft.LightSwitch.IEntityObject)() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.AVANCEDEOBRA)) Then
                Return New Global.LightSwitchApplication.Implementation.AVANCEDEOBRA()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.CONSTRUCCIONDEOBRA)) Then
                Return New Global.LightSwitchApplication.Implementation.CONSTRUCCIONDEOBRA()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.INSPECCIONMUNICIPAL)) Then
                Return New Global.LightSwitchApplication.Implementation.INSPECCIONMUNICIPAL()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.INSPECCION)) Then
                Return New Global.LightSwitchApplication.Implementation.INSPECCION()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.OBRA)) Then
                Return New Global.LightSwitchApplication.Implementation.OBRA()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.PERMISOS)) Then
                Return New Global.LightSwitchApplication.Implementation.PERMISOS()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.PLANO)) Then
                Return New Global.LightSwitchApplication.Implementation.PLANO()
            End If
            Return Nothing
        End Function
    
    #End Region
    
    End Class
    
    
    #Region "DataServiceImplementationFactory"
    <Global.System.ComponentModel.Composition.PartCreationPolicy(Global.System.ComponentModel.Composition.CreationPolicy.Shared)> _
    <Global.System.ComponentModel.Composition.Export(GetType(Global.Microsoft.LightSwitch.Internal.IDataServiceFactory))> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class __DataServiceFactory
        Inherits Global.Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    
        Protected Overrides Function CreateDataService(ByVal dataServiceType As Global.System.Type) As Global.Microsoft.LightSwitch.IDataService
            If dataServiceType.Equals(GetType(Global.LightSwitchApplication.ApplicationDataService)) Then
                Return New Global.LightSwitchApplication.ApplicationDataService()
            End If
            Return MyBase.CreateDataService(dataServiceType)
        End Function
    
        Protected Overrides Function CreateDataServiceImplementation(Of TDataService As Global.Microsoft.LightSwitch.IDataService)(ByVal dataService As TDataService) As Global.Microsoft.LightSwitch.Internal.IDataServiceImplementation
            If GetType(TDataService).Equals(GetType(Global.LightSwitchApplication.ApplicationDataService)) Then
                Return New Global.LightSwitchApplication.Implementation.ApplicationDataServiceImplementation(dataService)
            End If
            Return MyBase.CreateDataServiceImplementation(dataService)
        End Function
    End Class
    #End Region
    
    <Global.System.ComponentModel.Composition.PartCreationPolicy(Global.System.ComponentModel.Composition.CreationPolicy.Shared)> _
    <Global.System.ComponentModel.Composition.Export(GetType(Global.Microsoft.LightSwitch.Internal.ITypeMappingProvider))> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class __TypeMapping
        Implements Global.Microsoft.LightSwitch.Internal.ITypeMappingProvider
        Private Function GetImplementationType(ByVal definitionType As Global.System.Type) As Global.System.Type Implements Global.Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType
            If GetType(Global.LightSwitchApplication.AVANCEDEOBRA).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.AVANCEDEOBRA)
            End If
            If GetType(Global.LightSwitchApplication.CONSTRUCCIONDEOBRA).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.CONSTRUCCIONDEOBRA)
            End If
            If GetType(Global.LightSwitchApplication.INSPECCIONMUNICIPAL).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.INSPECCIONMUNICIPAL)
            End If
            If GetType(Global.LightSwitchApplication.INSPECCION).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.INSPECCION)
            End If
            If GetType(Global.LightSwitchApplication.OBRA).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.OBRA)
            End If
            If GetType(Global.LightSwitchApplication.PERMISOS).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.PERMISOS)
            End If
            If GetType(Global.LightSwitchApplication.PLANO).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.PLANO)
            End If
            Return Nothing
        End Function
    End Class
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class AVANCEDEOBRA
        Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation
        Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
     
        Private Property _ModifiedPropertyImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.Modified
        Get
            Return Me.Modified
        End Get
        Set(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
            Me.Modified = value
        End Set
    End Property
    
        Private Property _ModifiedByPropertyImplementation() As String Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.ModifiedBy
        Get
            Return Me.ModifiedBy
        End Get
        Set(ByVal value As String)
            Me.ModifiedBy = value
        End Set
    End Property
    
        Private Property _CreatedPropertyImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.Created
        Get
            Return Me.Created
        End Get
        Set(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
            Me.Created = value
        End Set
    End Property
    
        Private Property _CreatedByPropertyImplementation() As String Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.CreatedBy
        Get
            Return Me.CreatedBy
        End Get
        Set(ByVal value As String)
            Me.CreatedBy = value
        End Set
    End Property

        Private Property _IdImplementation() As Integer Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.Id
            Get
                Return Me.Id
            End Get
            Set(ByVal value As Integer)
                Me.Id = value
            End Set
        End Property
        
        Private Property _CATEGORIAImplementation() As String Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.CATEGORIA
            Get
                Return Me.CATEGORIA
            End Get
            Set(ByVal value As String)
                Me.CATEGORIA = value
            End Set
        End Property
        
        Private Property _TIPODEAVANCEImplementation() As String Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.TIPODEAVANCE
            Get
                Return Me.TIPODEAVANCE
            End Get
            Set(ByVal value As String)
                Me.TIPODEAVANCE = value
            End Set
        End Property
        
        Private Property _FECHAAVANCEImplementation() As Date Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.FECHAAVANCE
            Get
                Return Me.FECHAAVANCE
            End Get
            Set(ByVal value As Date)
                Me.FECHAAVANCE = value
            End Set
        End Property
        
        Private Property _FECHAPOSIBLEDEFINALIZACIONImplementation() As Date Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.FECHAPOSIBLEDEFINALIZACION
            Get
                Return Me.FECHAPOSIBLEDEFINALIZACION
            End Get
            Set(ByVal value As Date)
                Me.FECHAPOSIBLEDEFINALIZACION = value
            End Set
        End Property
        
        Private ReadOnly Property _CreatedByImplementation() As String Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.CreatedBy
            Get
                Return Me.CreatedBy
            End Get
        End Property
        
        Private ReadOnly Property _CreatedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.Created
            Get
                Return Me.Created
            End Get
        End Property
        
        Private ReadOnly Property _ModifiedByImplementation() As String Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.ModifiedBy
            Get
                Return Me.ModifiedBy
            End Get
        End Property
        
        Private ReadOnly Property _ModifiedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.Modified
            Get
                Return Me.Modified
            End Get
        End Property
        
        Private Property _RowVersionImplementation() As Byte() Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.RowVersion
            Get
                Return Me.RowVersion
            End Get
            Set(ByVal value As Byte())
                Me.RowVersion = value
            End Set
        End Property
        
        Private Property _CONSTRUCCIONDEOBRAImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.CONSTRUCCIONDEOBRA
            Get
                Return Me.CONSTRUCCIONDEOBRA
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.CONSTRUCCIONDEOBRA = DirectCast(value, Global.LightSwitchApplication.Implementation.CONSTRUCCIONDEOBRA)
                If Me.__host IsNot Nothing Then
                    Me.__host.RaisePropertyChanged("CONSTRUCCIONDEOBRA")
                End If
            End Set
        End Property
        
        Private Sub OnAVANCEDEOBRA_CONSTRUCCIONDEOBRAChanged()
            If Me.__host IsNot Nothing Then
                Me.__host.RaisePropertyChanged("CONSTRUCCIONDEOBRA")
            End If
        End Sub
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class CONSTRUCCIONDEOBRA
        Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation
        Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
     
        Private Property _ModifiedPropertyImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.Modified
        Get
            Return Me.Modified
        End Get
        Set(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
            Me.Modified = value
        End Set
    End Property
    
        Private Property _ModifiedByPropertyImplementation() As String Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.ModifiedBy
        Get
            Return Me.ModifiedBy
        End Get
        Set(ByVal value As String)
            Me.ModifiedBy = value
        End Set
    End Property
    
        Private Property _CreatedPropertyImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.Created
        Get
            Return Me.Created
        End Get
        Set(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
            Me.Created = value
        End Set
    End Property
    
        Private Property _CreatedByPropertyImplementation() As String Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.CreatedBy
        Get
            Return Me.CreatedBy
        End Get
        Set(ByVal value As String)
            Me.CreatedBy = value
        End Set
    End Property

        Private Property _IdImplementation() As Integer Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.Id
            Get
                Return Me.Id
            End Get
            Set(ByVal value As Integer)
                Me.Id = value
            End Set
        End Property
        
        Private Property _CODIGOImplementation() As String Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.CODIGO
            Get
                Return Me.CODIGO
            End Get
            Set(ByVal value As String)
                Me.CODIGO = value
            End Set
        End Property
        
        Private Property _TIPOImplementation() As String Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.TIPO
            Get
                Return Me.TIPO
            End Get
            Set(ByVal value As String)
                Me.TIPO = value
            End Set
        End Property
        
        Private Property _FECHAImplementation() As Date Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.FECHA
            Get
                Return Me.FECHA
            End Get
            Set(ByVal value As Date)
                Me.FECHA = value
            End Set
        End Property
        
        Private ReadOnly Property _CreatedByImplementation() As String Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.CreatedBy
            Get
                Return Me.CreatedBy
            End Get
        End Property
        
        Private ReadOnly Property _CreatedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.Created
            Get
                Return Me.Created
            End Get
        End Property
        
        Private ReadOnly Property _ModifiedByImplementation() As String Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.ModifiedBy
            Get
                Return Me.ModifiedBy
            End Get
        End Property
        
        Private ReadOnly Property _ModifiedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.Modified
            Get
                Return Me.Modified
            End Get
        End Property
        
        Private Property _RowVersionImplementation() As Byte() Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.RowVersion
            Get
                Return Me.RowVersion
            End Get
            Set(ByVal value As Byte())
                Me.RowVersion = value
            End Set
        End Property
        
        Private Property _OBRAImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.OBRA
            Get
                Return Me.OBRA
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.OBRA = DirectCast(value, Global.LightSwitchApplication.Implementation.OBRA)
                If Me.__host IsNot Nothing Then
                    Me.__host.RaisePropertyChanged("OBRA")
                End If
            End Set
        End Property
        
        Private ReadOnly Property _AVANCEDEOBRAsImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.AVANCEDEOBRAs
            Get
                Return Me.AVANCEDEOBRAs
            End Get
        End Property
        
        Private Sub OnOBRA_CONSTRUCCIONDEOBRAChanged()
            If Me.__host IsNot Nothing Then
                Me.__host.RaisePropertyChanged("OBRA")
            End If
        End Sub
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class INSPECCIONMUNICIPAL
        Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation
        Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
     
        Private Property _ModifiedPropertyImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.Modified
        Get
            Return Me.Modified
        End Get
        Set(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
            Me.Modified = value
        End Set
    End Property
    
        Private Property _ModifiedByPropertyImplementation() As String Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.ModifiedBy
        Get
            Return Me.ModifiedBy
        End Get
        Set(ByVal value As String)
            Me.ModifiedBy = value
        End Set
    End Property
    
        Private Property _CreatedPropertyImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.Created
        Get
            Return Me.Created
        End Get
        Set(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
            Me.Created = value
        End Set
    End Property
    
        Private Property _CreatedByPropertyImplementation() As String Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.CreatedBy
        Get
            Return Me.CreatedBy
        End Get
        Set(ByVal value As String)
            Me.CreatedBy = value
        End Set
    End Property

        Private Property _IdImplementation() As Integer Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation.Id
            Get
                Return Me.Id
            End Get
            Set(ByVal value As Integer)
                Me.Id = value
            End Set
        End Property
        
        Private Property _FECHAREALIZADAImplementation() As Date Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation.FECHAREALIZADA
            Get
                Return Me.FECHAREALIZADA
            End Get
            Set(ByVal value As Date)
                Me.FECHAREALIZADA = value
            End Set
        End Property
        
        Private Property _ESTADOImplementation() As String Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation.ESTADO
            Get
                Return Me.ESTADO
            End Get
            Set(ByVal value As String)
                Me.ESTADO = value
            End Set
        End Property
        
        Private Property _FECHAESTADOImplementation() As Date Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation.FECHAESTADO
            Get
                Return Me.FECHAESTADO
            End Get
            Set(ByVal value As Date)
                Me.FECHAESTADO = value
            End Set
        End Property
        
        Private ReadOnly Property _CreatedByImplementation() As String Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation.CreatedBy
            Get
                Return Me.CreatedBy
            End Get
        End Property
        
        Private ReadOnly Property _CreatedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation.Created
            Get
                Return Me.Created
            End Get
        End Property
        
        Private ReadOnly Property _ModifiedByImplementation() As String Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation.ModifiedBy
            Get
                Return Me.ModifiedBy
            End Get
        End Property
        
        Private ReadOnly Property _ModifiedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation.Modified
            Get
                Return Me.Modified
            End Get
        End Property
        
        Private Property _RowVersionImplementation() As Byte() Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation.RowVersion
            Get
                Return Me.RowVersion
            End Get
            Set(ByVal value As Byte())
                Me.RowVersion = value
            End Set
        End Property
        
        Private Property _OBRAImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation.OBRA
            Get
                Return Me.OBRA
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.OBRA = DirectCast(value, Global.LightSwitchApplication.Implementation.OBRA)
                If Me.__host IsNot Nothing Then
                    Me.__host.RaisePropertyChanged("OBRA")
                End If
            End Set
        End Property
        
        Private Sub OnINSPECCIONMUNICIPAL_OBRAChanged()
            If Me.__host IsNot Nothing Then
                Me.__host.RaisePropertyChanged("OBRA")
            End If
        End Sub
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class INSPECCION
        Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation
        Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
     
        Private Property _ModifiedPropertyImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.Modified
        Get
            Return Me.Modified
        End Get
        Set(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
            Me.Modified = value
        End Set
    End Property
    
        Private Property _ModifiedByPropertyImplementation() As String Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.ModifiedBy
        Get
            Return Me.ModifiedBy
        End Get
        Set(ByVal value As String)
            Me.ModifiedBy = value
        End Set
    End Property
    
        Private Property _CreatedPropertyImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.Created
        Get
            Return Me.Created
        End Get
        Set(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
            Me.Created = value
        End Set
    End Property
    
        Private Property _CreatedByPropertyImplementation() As String Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.CreatedBy
        Get
            Return Me.CreatedBy
        End Get
        Set(ByVal value As String)
            Me.CreatedBy = value
        End Set
    End Property

        Private Property _IdImplementation() As Integer Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.Id
            Get
                Return Me.Id
            End Get
            Set(ByVal value As Integer)
                Me.Id = value
            End Set
        End Property
        
        Private Property _FECHAImplementation() As Date Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.FECHA
            Get
                Return Me.FECHA
            End Get
            Set(ByVal value As Date)
                Me.FECHA = value
            End Set
        End Property
        
        Private Property _CATEGORIAImplementation() As String Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.CATEGORIA
            Get
                Return Me.CATEGORIA
            End Get
            Set(ByVal value As String)
                Me.CATEGORIA = value
            End Set
        End Property
        
        Private Property _ESTADOImplementation() As String Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.ESTADO
            Get
                Return Me.ESTADO
            End Get
            Set(ByVal value As String)
                Me.ESTADO = value
            End Set
        End Property
        
        Private Property _FECHADEESTADOImplementation() As Date Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.FECHADEESTADO
            Get
                Return Me.FECHADEESTADO
            End Get
            Set(ByVal value As Date)
                Me.FECHADEESTADO = value
            End Set
        End Property
        
        Private ReadOnly Property _CreatedByImplementation() As String Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.CreatedBy
            Get
                Return Me.CreatedBy
            End Get
        End Property
        
        Private ReadOnly Property _CreatedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.Created
            Get
                Return Me.Created
            End Get
        End Property
        
        Private ReadOnly Property _ModifiedByImplementation() As String Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.ModifiedBy
            Get
                Return Me.ModifiedBy
            End Get
        End Property
        
        Private ReadOnly Property _ModifiedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.Modified
            Get
                Return Me.Modified
            End Get
        End Property
        
        Private Property _RowVersionImplementation() As Byte() Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.RowVersion
            Get
                Return Me.RowVersion
            End Get
            Set(ByVal value As Byte())
                Me.RowVersion = value
            End Set
        End Property
        
        Private Property _OBRAImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.OBRA
            Get
                Return Me.OBRA
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.OBRA = DirectCast(value, Global.LightSwitchApplication.Implementation.OBRA)
                If Me.__host IsNot Nothing Then
                    Me.__host.RaisePropertyChanged("OBRA")
                End If
            End Set
        End Property
        
        Private Sub OnINSPECCION_OBRAChanged()
            If Me.__host IsNot Nothing Then
                Me.__host.RaisePropertyChanged("OBRA")
            End If
        End Sub
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class OBRA
        Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation
        Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
     
        Private Property _ModifiedPropertyImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.Modified
        Get
            Return Me.Modified
        End Get
        Set(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
            Me.Modified = value
        End Set
    End Property
    
        Private Property _ModifiedByPropertyImplementation() As String Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.ModifiedBy
        Get
            Return Me.ModifiedBy
        End Get
        Set(ByVal value As String)
            Me.ModifiedBy = value
        End Set
    End Property
    
        Private Property _CreatedPropertyImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.Created
        Get
            Return Me.Created
        End Get
        Set(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
            Me.Created = value
        End Set
    End Property
    
        Private Property _CreatedByPropertyImplementation() As String Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.CreatedBy
        Get
            Return Me.CreatedBy
        End Get
        Set(ByVal value As String)
            Me.CreatedBy = value
        End Set
    End Property

        Private Property _IdImplementation() As Integer Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.Id
            Get
                Return Me.Id
            End Get
            Set(ByVal value As Integer)
                Me.Id = value
            End Set
        End Property
        
        Private Property _CODIGOImplementation() As String Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.CODIGO
            Get
                Return Me.CODIGO
            End Get
            Set(ByVal value As String)
                Me.CODIGO = value
            End Set
        End Property
        
        Private Property _NOMBREImplementation() As String Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.NOMBRE
            Get
                Return Me.NOMBRE
            End Get
            Set(ByVal value As String)
                Me.NOMBRE = value
            End Set
        End Property
        
        Private Property _SUPERFICIEENMETROSCUADRADOSImplementation() As Double Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.SUPERFICIEENMETROSCUADRADOS
            Get
                Return Me.SUPERFICIEENMETROSCUADRADOS
            End Get
            Set(ByVal value As Double)
                Me.SUPERFICIEENMETROSCUADRADOS = value
            End Set
        End Property
        
        Private Property _FECHAINICIOImplementation() As Date Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.FECHAINICIO
            Get
                Return Me.FECHAINICIO
            End Get
            Set(ByVal value As Date)
                Me.FECHAINICIO = value
            End Set
        End Property
        
        Private Property _FECHAPROBABLEFINImplementation() As Date Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.FECHAPROBABLEFIN
            Get
                Return Me.FECHAPROBABLEFIN
            End Get
            Set(ByVal value As Date)
                Me.FECHAPROBABLEFIN = value
            End Set
        End Property
        
        Private ReadOnly Property _CreatedByImplementation() As String Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.CreatedBy
            Get
                Return Me.CreatedBy
            End Get
        End Property
        
        Private ReadOnly Property _CreatedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.Created
            Get
                Return Me.Created
            End Get
        End Property
        
        Private ReadOnly Property _ModifiedByImplementation() As String Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.ModifiedBy
            Get
                Return Me.ModifiedBy
            End Get
        End Property
        
        Private ReadOnly Property _ModifiedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.Modified
            Get
                Return Me.Modified
            End Get
        End Property
        
        Private Property _RowVersionImplementation() As Byte() Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.RowVersion
            Get
                Return Me.RowVersion
            End Get
            Set(ByVal value As Byte())
                Me.RowVersion = value
            End Set
        End Property
        
        Private ReadOnly Property _CONSTRUCCIONDEOBRAsImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.CONSTRUCCIONDEOBRAs
            Get
                Return Me.CONSTRUCCIONDEOBRAs
            End Get
        End Property
        
        Private ReadOnly Property _INSPECCIONsImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.INSPECCIONs
            Get
                Return Me.INSPECCIONs
            End Get
        End Property
        
        Private ReadOnly Property _PLANOesImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.PLANOes
            Get
                Return Me.PLANOes
            End Get
        End Property
        
        Private ReadOnly Property _PERMISOSCollectionImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.PERMISOSCollection
            Get
                Return Me.PERMISOSCollection
            End Get
        End Property
        
        Private ReadOnly Property _INSPECCIONMUNICIPALsImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.INSPECCIONMUNICIPALs
            Get
                Return Me.INSPECCIONMUNICIPALs
            End Get
        End Property
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class PERMISOS
        Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation
        Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
     
        Private Property _ModifiedPropertyImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.Modified
        Get
            Return Me.Modified
        End Get
        Set(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
            Me.Modified = value
        End Set
    End Property
    
        Private Property _ModifiedByPropertyImplementation() As String Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.ModifiedBy
        Get
            Return Me.ModifiedBy
        End Get
        Set(ByVal value As String)
            Me.ModifiedBy = value
        End Set
    End Property
    
        Private Property _CreatedPropertyImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.Created
        Get
            Return Me.Created
        End Get
        Set(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
            Me.Created = value
        End Set
    End Property
    
        Private Property _CreatedByPropertyImplementation() As String Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.CreatedBy
        Get
            Return Me.CreatedBy
        End Get
        Set(ByVal value As String)
            Me.CreatedBy = value
        End Set
    End Property

        Private Property _IdImplementation() As Integer Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.Id
            Get
                Return Me.Id
            End Get
            Set(ByVal value As Integer)
                Me.Id = value
            End Set
        End Property
        
        Private Property _CODIGOImplementation() As String Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.CODIGO
            Get
                Return Me.CODIGO
            End Get
            Set(ByVal value As String)
                Me.CODIGO = value
            End Set
        End Property
        
        Private Property _NOMBREImplementation() As String Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.NOMBRE
            Get
                Return Me.NOMBRE
            End Get
            Set(ByVal value As String)
                Me.NOMBRE = value
            End Set
        End Property
        
        Private Property _FECHADEPRESENTACIONImplementation() As Date Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.FECHADEPRESENTACION
            Get
                Return Me.FECHADEPRESENTACION
            End Get
            Set(ByVal value As Date)
                Me.FECHADEPRESENTACION = value
            End Set
        End Property
        
        Private Property _FECHADEAPROBACIONImplementation() As Date Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.FECHADEAPROBACION
            Get
                Return Me.FECHADEAPROBACION
            End Get
            Set(ByVal value As Date)
                Me.FECHADEAPROBACION = value
            End Set
        End Property
        
        Private ReadOnly Property _CreatedByImplementation() As String Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.CreatedBy
            Get
                Return Me.CreatedBy
            End Get
        End Property
        
        Private ReadOnly Property _CreatedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.Created
            Get
                Return Me.Created
            End Get
        End Property
        
        Private ReadOnly Property _ModifiedByImplementation() As String Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.ModifiedBy
            Get
                Return Me.ModifiedBy
            End Get
        End Property
        
        Private ReadOnly Property _ModifiedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.Modified
            Get
                Return Me.Modified
            End Get
        End Property
        
        Private Property _RowVersionImplementation() As Byte() Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.RowVersion
            Get
                Return Me.RowVersion
            End Get
            Set(ByVal value As Byte())
                Me.RowVersion = value
            End Set
        End Property
        
        Private Property _OBRAImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.OBRA
            Get
                Return Me.OBRA
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.OBRA = DirectCast(value, Global.LightSwitchApplication.Implementation.OBRA)
                If Me.__host IsNot Nothing Then
                    Me.__host.RaisePropertyChanged("OBRA")
                End If
            End Set
        End Property
        
        Private Sub OnPERMISOS_OBRAChanged()
            If Me.__host IsNot Nothing Then
                Me.__host.RaisePropertyChanged("OBRA")
            End If
        End Sub
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class PLANO
        Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation
        Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
     
        Private Property _ModifiedPropertyImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.Modified
        Get
            Return Me.Modified
        End Get
        Set(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
            Me.Modified = value
        End Set
    End Property
    
        Private Property _ModifiedByPropertyImplementation() As String Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.ModifiedBy
        Get
            Return Me.ModifiedBy
        End Get
        Set(ByVal value As String)
            Me.ModifiedBy = value
        End Set
    End Property
    
        Private Property _CreatedPropertyImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.Created
        Get
            Return Me.Created
        End Get
        Set(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
            Me.Created = value
        End Set
    End Property
    
        Private Property _CreatedByPropertyImplementation() As String Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.CreatedBy
        Get
            Return Me.CreatedBy
        End Get
        Set(ByVal value As String)
            Me.CreatedBy = value
        End Set
    End Property

        Private Property _IdImplementation() As Integer Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.Id
            Get
                Return Me.Id
            End Get
            Set(ByVal value As Integer)
                Me.Id = value
            End Set
        End Property
        
        Private Property _NUMEROImplementation() As Integer Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.NUMERO
            Get
                Return Me.NUMERO
            End Get
            Set(ByVal value As Integer)
                Me.NUMERO = value
            End Set
        End Property
        
        Private Property _TIPOImplementation() As String Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.TIPO
            Get
                Return Me.TIPO
            End Get
            Set(ByVal value As String)
                Me.TIPO = value
            End Set
        End Property
        
        Private Property _FECHAREALIZADOImplementation() As Date Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.FECHAREALIZADO
            Get
                Return Me.FECHAREALIZADO
            End Get
            Set(ByVal value As Date)
                Me.FECHAREALIZADO = value
            End Set
        End Property
        
        Private Property _FECHAAPROBADOImplementation() As Date Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.FECHAAPROBADO
            Get
                Return Me.FECHAAPROBADO
            End Get
            Set(ByVal value As Date)
                Me.FECHAAPROBADO = value
            End Set
        End Property
        
        Private ReadOnly Property _CreatedByImplementation() As String Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.CreatedBy
            Get
                Return Me.CreatedBy
            End Get
        End Property
        
        Private ReadOnly Property _CreatedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.Created
            Get
                Return Me.Created
            End Get
        End Property
        
        Private ReadOnly Property _ModifiedByImplementation() As String Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.ModifiedBy
            Get
                Return Me.ModifiedBy
            End Get
        End Property
        
        Private ReadOnly Property _ModifiedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.Modified
            Get
                Return Me.Modified
            End Get
        End Property
        
        Private Property _RowVersionImplementation() As Byte() Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.RowVersion
            Get
                Return Me.RowVersion
            End Get
            Set(ByVal value As Byte())
                Me.RowVersion = value
            End Set
        End Property
        
        Private Property _OBRAImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.OBRA
            Get
                Return Me.OBRA
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.OBRA = DirectCast(value, Global.LightSwitchApplication.Implementation.OBRA)
                If Me.__host IsNot Nothing Then
                    Me.__host.RaisePropertyChanged("OBRA")
                End If
            End Set
        End Property
        
        Private Sub OnPLANO_OBRAChanged()
            If Me.__host IsNot Nothing Then
                Me.__host.RaisePropertyChanged("OBRA")
            End If
        End Sub
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
End Namespace

