
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __INSPECCIONMUNICIPAL = LightSwitchApplication.INSPECCIONMUNICIPAL

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No hay ninguna descripción modelada
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    Public NotInheritable Partial Class INSPECCIONMUNICIPAL
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Inicializa una nueva instancia de la entidad INSPECCIONMUNICIPAL.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __INSPECCIONMUNICIPAL))
            MyBase.New(entitySet)
            
            __INSPECCIONMUNICIPAL.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub INSPECCIONMUNICIPAL_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub INSPECCIONMUNICIPAL_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return TryCast(Global.LightSwitchApplication.Application.Current, Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace))
            End Get
        End Property
        
        ''' <summary>
        ''' Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Id As Integer
            Get
                Return __INSPECCIONMUNICIPAL.DetailsClass.GetValue(Me, __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.Id)
            End Get
            Set
                __INSPECCIONMUNICIPAL.DetailsClass.SetValue(Me, __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.Id, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property FECHAREALIZADA As Date
            Get
                Return __INSPECCIONMUNICIPAL.DetailsClass.GetValue(Me, __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.FECHAREALIZADA)
            End Get
            Set
                __INSPECCIONMUNICIPAL.DetailsClass.SetValue(Me, __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.FECHAREALIZADA, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FECHAREALIZADA_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FECHAREALIZADA_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FECHAREALIZADA_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ESTADO As String
            Get
                Return __INSPECCIONMUNICIPAL.DetailsClass.GetValue(Me, __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.ESTADO)
            End Get
            Set
                __INSPECCIONMUNICIPAL.DetailsClass.SetValue(Me, __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.ESTADO, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ESTADO_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ESTADO_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ESTADO_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property FECHAESTADO As Date
            Get
                Return __INSPECCIONMUNICIPAL.DetailsClass.GetValue(Me, __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.FECHAESTADO)
            End Get
            Set
                __INSPECCIONMUNICIPAL.DetailsClass.SetValue(Me, __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.FECHAESTADO, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FECHAESTADO_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FECHAESTADO_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FECHAESTADO_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property CreatedBy As String
            Get
                Return __INSPECCIONMUNICIPAL.DetailsClass.GetValue(Me, __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.CreatedBy)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreatedBy_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreatedBy_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreatedBy_Changed()
        End Sub
        Public ReadOnly Property CreatedByInfo() As Global.Microsoft.LightSwitch.Framework.Server.PersonInfo
            Get
                Dim personInfoFactory As Global.Microsoft.LightSwitch.Server.IPersonInfoFactory = Global.LightSwitchApplication.Application.Current.GetPersonInfoFactory()
                Return DirectCast(personInfoFactory.ResolvePerson(Me.CreatedBy), Global.Microsoft.LightSwitch.Framework.Server.PersonInfo)
            End Get
        End Property

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Created As Global.System.Nullable(Of Global.System.DateTimeOffset)
            Get
                Return __INSPECCIONMUNICIPAL.DetailsClass.GetValue(Me, __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.Created)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Created_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Created_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Created_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property ModifiedBy As String
            Get
                Return __INSPECCIONMUNICIPAL.DetailsClass.GetValue(Me, __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.ModifiedBy)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ModifiedBy_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ModifiedBy_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ModifiedBy_Changed()
        End Sub
        Public ReadOnly Property ModifiedByInfo() As Global.Microsoft.LightSwitch.Framework.Server.PersonInfo
            Get
                Dim personInfoFactory As Global.Microsoft.LightSwitch.Server.IPersonInfoFactory = Global.LightSwitchApplication.Application.Current.GetPersonInfoFactory()
                Return DirectCast(personInfoFactory.ResolvePerson(Me.ModifiedBy), Global.Microsoft.LightSwitch.Framework.Server.PersonInfo)
            End Get
        End Property

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Modified As Global.System.Nullable(Of Global.System.DateTimeOffset)
            Get
                Return __INSPECCIONMUNICIPAL.DetailsClass.GetValue(Me, __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.Modified)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Modified_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Modified_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Modified_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property RowVersion As Byte()
            Get
                Return __INSPECCIONMUNICIPAL.DetailsClass.GetValue(Me, __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.RowVersion)
            End Get
            Set
                __INSPECCIONMUNICIPAL.DetailsClass.SetValue(Me, __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.RowVersion, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property OBRA As Global.LightSwitchApplication.OBRA
            Get
                Return __INSPECCIONMUNICIPAL.DetailsClass.GetValue(Me, __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.OBRA)
            End Get
            Set
                __INSPECCIONMUNICIPAL.DetailsClass.SetValue(Me, __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.OBRA, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub OBRA_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub OBRA_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub OBRA_Changed()
        End Sub

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __INSPECCIONMUNICIPAL, _
                __INSPECCIONMUNICIPAL.DetailsClass, _
                __INSPECCIONMUNICIPAL.DetailsClass.IImplementation, _
                __INSPECCIONMUNICIPAL.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.Id
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __INSPECCIONMUNICIPALEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass).Entry( _
                    AddressOf __INSPECCIONMUNICIPAL.DetailsClass.__INSPECCIONMUNICIPAL_CreateNew, _
                    AddressOf __INSPECCIONMUNICIPAL.DetailsClass.__INSPECCIONMUNICIPAL_Created, _
                    AddressOf __INSPECCIONMUNICIPAL.DetailsClass.__INSPECCIONMUNICIPAL_AllowSaveWithErrors)
            Private Shared Function __INSPECCIONMUNICIPAL_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __INSPECCIONMUNICIPAL)) As __INSPECCIONMUNICIPAL
                Return New __INSPECCIONMUNICIPAL(es)
            End Function
            Private Shared Sub __INSPECCIONMUNICIPAL_Created(e As __INSPECCIONMUNICIPAL)
                e.INSPECCIONMUNICIPAL_Created()
            End Sub
            Private Shared Function __INSPECCIONMUNICIPAL_AllowSaveWithErrors(e As __INSPECCIONMUNICIPAL) As Boolean
                Dim result As Boolean = False
                e.INSPECCIONMUNICIPAL_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __INSPECCIONMUNICIPAL.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.Id),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property FECHAREALIZADA As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Date)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.FECHAREALIZADA),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Date))
                    End Get
                End Property
                
                Public ReadOnly Property ESTADO As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.ESTADO),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property FECHAESTADO As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Date)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.FECHAESTADO),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Date))
                    End Get
                End Property
                
                Public ReadOnly Property CreatedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.CreatedBy),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Created As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.Created),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)))
                    End Get
                End Property
                
                Public ReadOnly Property ModifiedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.ModifiedBy),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Modified As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.Modified),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)))
                    End Get
                End Property
                
                Public ReadOnly Property RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Byte())
                    Get
                        Return TryCast(
                            MyBase.GetItem(__INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.RowVersion),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Byte()))
                    End Get
                End Property
                
                Public ReadOnly Property OBRA As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Global.LightSwitchApplication.OBRA)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.OBRA),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Global.LightSwitchApplication.OBRA))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property Id As Integer
                Shadows Property FECHAREALIZADA As Date
                Shadows Property ESTADO As String
                Shadows Property FECHAESTADO As Date
                Shadows ReadOnly Property CreatedBy As String
                Shadows ReadOnly Property Created As Global.System.Nullable(Of Global.System.DateTimeOffset)
                Shadows ReadOnly Property ModifiedBy As String
                Shadows ReadOnly Property Modified As Global.System.Nullable(Of Global.System.DateTimeOffset)
                Shadows Property RowVersion As Byte()
                Shadows Property OBRA As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Integer).Entry( _
                        "Id", _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._Id_Stub, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._Id_Validate, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._Id_GetImplementationValue, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._Id_SetImplementationValue, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._Id_OnValueChanged)
                Private Shared Sub _Id_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __INSPECCIONMUNICIPAL.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Integer).Data), d As __INSPECCIONMUNICIPAL.DetailsClass, sf As Object)
                    c(d, d._Id, sf)
                End Sub
                Private Shared Function _Id_ComputeIsReadOnly(e As __INSPECCIONMUNICIPAL) As Boolean
                    Dim result As Boolean = False
                    e.Id_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Id_Validate(e As __INSPECCIONMUNICIPAL, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Id_Validate(r)
                End Sub
                Private Shared Function _Id_GetImplementationValue(d As __INSPECCIONMUNICIPAL.DetailsClass) As Integer
                    Return d.ImplementationEntity.Id
                End Function
                Private Shared Sub _Id_SetImplementationValue(d As __INSPECCIONMUNICIPAL.DetailsClass, v As Integer)
                    d.ImplementationEntity.Id = v
                End Sub
                Private Shared Sub _Id_OnValueChanged(e As __INSPECCIONMUNICIPAL)
                    e.Id_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly FECHAREALIZADA As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Date).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Date).Entry( _
                        "FECHAREALIZADA", _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._FECHAREALIZADA_Stub, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._FECHAREALIZADA_ComputeIsReadOnly, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._FECHAREALIZADA_Validate, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._FECHAREALIZADA_GetImplementationValue, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._FECHAREALIZADA_SetImplementationValue, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._FECHAREALIZADA_OnValueChanged)
                Private Shared Sub _FECHAREALIZADA_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __INSPECCIONMUNICIPAL.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Date).Data), d As __INSPECCIONMUNICIPAL.DetailsClass, sf As Object)
                    c(d, d._FECHAREALIZADA, sf)
                End Sub
                Private Shared Function _FECHAREALIZADA_ComputeIsReadOnly(e As __INSPECCIONMUNICIPAL) As Boolean
                    Dim result As Boolean = False
                    e.FECHAREALIZADA_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _FECHAREALIZADA_Validate(e As __INSPECCIONMUNICIPAL, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.FECHAREALIZADA_Validate(r)
                End Sub
                Private Shared Function _FECHAREALIZADA_GetImplementationValue(d As __INSPECCIONMUNICIPAL.DetailsClass) As Date
                    Return d.ImplementationEntity.FECHAREALIZADA
                End Function
                Private Shared Sub _FECHAREALIZADA_SetImplementationValue(d As __INSPECCIONMUNICIPAL.DetailsClass, v As Date)
                    d.ImplementationEntity.FECHAREALIZADA = __INSPECCIONMUNICIPAL.DetailsClass.TruncateDate(v)
                End Sub
                Private Shared Sub _FECHAREALIZADA_OnValueChanged(e As __INSPECCIONMUNICIPAL)
                    e.FECHAREALIZADA_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ESTADO As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, String).Entry( _
                        "ESTADO", _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._ESTADO_Stub, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._ESTADO_ComputeIsReadOnly, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._ESTADO_Validate, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._ESTADO_GetImplementationValue, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._ESTADO_SetImplementationValue, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._ESTADO_OnValueChanged)
                Private Shared Sub _ESTADO_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __INSPECCIONMUNICIPAL.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, String).Data), d As __INSPECCIONMUNICIPAL.DetailsClass, sf As Object)
                    c(d, d._ESTADO, sf)
                End Sub
                Private Shared Function _ESTADO_ComputeIsReadOnly(e As __INSPECCIONMUNICIPAL) As Boolean
                    Dim result As Boolean = False
                    e.ESTADO_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ESTADO_Validate(e As __INSPECCIONMUNICIPAL, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ESTADO_Validate(r)
                End Sub
                Private Shared Function _ESTADO_GetImplementationValue(d As __INSPECCIONMUNICIPAL.DetailsClass) As String
                    Return d.ImplementationEntity.ESTADO
                End Function
                Private Shared Sub _ESTADO_SetImplementationValue(d As __INSPECCIONMUNICIPAL.DetailsClass, v As String)
                    d.ImplementationEntity.ESTADO = v
                End Sub
                Private Shared Sub _ESTADO_OnValueChanged(e As __INSPECCIONMUNICIPAL)
                    e.ESTADO_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly FECHAESTADO As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Date).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Date).Entry( _
                        "FECHAESTADO", _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._FECHAESTADO_Stub, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._FECHAESTADO_ComputeIsReadOnly, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._FECHAESTADO_Validate, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._FECHAESTADO_GetImplementationValue, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._FECHAESTADO_SetImplementationValue, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._FECHAESTADO_OnValueChanged)
                Private Shared Sub _FECHAESTADO_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __INSPECCIONMUNICIPAL.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Date).Data), d As __INSPECCIONMUNICIPAL.DetailsClass, sf As Object)
                    c(d, d._FECHAESTADO, sf)
                End Sub
                Private Shared Function _FECHAESTADO_ComputeIsReadOnly(e As __INSPECCIONMUNICIPAL) As Boolean
                    Dim result As Boolean = False
                    e.FECHAESTADO_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _FECHAESTADO_Validate(e As __INSPECCIONMUNICIPAL, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.FECHAESTADO_Validate(r)
                End Sub
                Private Shared Function _FECHAESTADO_GetImplementationValue(d As __INSPECCIONMUNICIPAL.DetailsClass) As Date
                    Return d.ImplementationEntity.FECHAESTADO
                End Function
                Private Shared Sub _FECHAESTADO_SetImplementationValue(d As __INSPECCIONMUNICIPAL.DetailsClass, v As Date)
                    d.ImplementationEntity.FECHAESTADO = __INSPECCIONMUNICIPAL.DetailsClass.TruncateDate(v)
                End Sub
                Private Shared Sub _FECHAESTADO_OnValueChanged(e As __INSPECCIONMUNICIPAL)
                    e.FECHAESTADO_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CreatedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, String).Entry( _
                        "CreatedBy", _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._CreatedBy_Stub, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._CreatedBy_Validate, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue, _
                        Nothing, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged)
                Private Shared Sub _CreatedBy_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __INSPECCIONMUNICIPAL.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, String).Data), d As __INSPECCIONMUNICIPAL.DetailsClass, sf As Object)
                    c(d, d._CreatedBy, sf)
                End Sub
                Private Shared Function _CreatedBy_ComputeIsReadOnly(e As __INSPECCIONMUNICIPAL) As Boolean
                    Dim result As Boolean = False
                    e.CreatedBy_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _CreatedBy_Validate(e As __INSPECCIONMUNICIPAL, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.CreatedBy_Validate(r)
                End Sub
                Private Shared Function _CreatedBy_GetImplementationValue(d As __INSPECCIONMUNICIPAL.DetailsClass) As String
                    Return d.ImplementationEntity.CreatedBy
                End Function
                Private Shared Sub _CreatedBy_OnValueChanged(e As __INSPECCIONMUNICIPAL)
                    e.CreatedBy_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Created As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry( _
                        "Created", _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._Created_Stub, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._Created_Validate, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._Created_GetImplementationValue, _
                        Nothing, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._Created_OnValueChanged)
                Private Shared Sub _Created_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __INSPECCIONMUNICIPAL.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data), d As __INSPECCIONMUNICIPAL.DetailsClass, sf As Object)
                    c(d, d._Created, sf)
                End Sub
                Private Shared Function _Created_ComputeIsReadOnly(e As __INSPECCIONMUNICIPAL) As Boolean
                    Dim result As Boolean = False
                    e.Created_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Created_Validate(e As __INSPECCIONMUNICIPAL, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Created_Validate(r)
                End Sub
                Private Shared Function _Created_GetImplementationValue(d As __INSPECCIONMUNICIPAL.DetailsClass) As Global.System.Nullable(Of Global.System.DateTimeOffset)
                    Return d.ImplementationEntity.Created
                End Function
                Private Shared Sub _Created_OnValueChanged(e As __INSPECCIONMUNICIPAL)
                    e.Created_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ModifiedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, String).Entry( _
                        "ModifiedBy", _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._ModifiedBy_Stub, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._ModifiedBy_Validate, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue, _
                        Nothing, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged)
                Private Shared Sub _ModifiedBy_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __INSPECCIONMUNICIPAL.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, String).Data), d As __INSPECCIONMUNICIPAL.DetailsClass, sf As Object)
                    c(d, d._ModifiedBy, sf)
                End Sub
                Private Shared Function _ModifiedBy_ComputeIsReadOnly(e As __INSPECCIONMUNICIPAL) As Boolean
                    Dim result As Boolean = False
                    e.ModifiedBy_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ModifiedBy_Validate(e As __INSPECCIONMUNICIPAL, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ModifiedBy_Validate(r)
                End Sub
                Private Shared Function _ModifiedBy_GetImplementationValue(d As __INSPECCIONMUNICIPAL.DetailsClass) As String
                    Return d.ImplementationEntity.ModifiedBy
                End Function
                Private Shared Sub _ModifiedBy_OnValueChanged(e As __INSPECCIONMUNICIPAL)
                    e.ModifiedBy_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Modified As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry( _
                        "Modified", _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._Modified_Stub, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._Modified_Validate, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._Modified_GetImplementationValue, _
                        Nothing, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._Modified_OnValueChanged)
                Private Shared Sub _Modified_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __INSPECCIONMUNICIPAL.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data), d As __INSPECCIONMUNICIPAL.DetailsClass, sf As Object)
                    c(d, d._Modified, sf)
                End Sub
                Private Shared Function _Modified_ComputeIsReadOnly(e As __INSPECCIONMUNICIPAL) As Boolean
                    Dim result As Boolean = False
                    e.Modified_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Modified_Validate(e As __INSPECCIONMUNICIPAL, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Modified_Validate(r)
                End Sub
                Private Shared Function _Modified_GetImplementationValue(d As __INSPECCIONMUNICIPAL.DetailsClass) As Global.System.Nullable(Of Global.System.DateTimeOffset)
                    Return d.ImplementationEntity.Modified
                End Function
                Private Shared Sub _Modified_OnValueChanged(e As __INSPECCIONMUNICIPAL)
                    e.Modified_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Byte()).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Byte()).Entry( _
                        "RowVersion", _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._RowVersion_Stub, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._RowVersion_Validate, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged)
                Private Shared Sub _RowVersion_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __INSPECCIONMUNICIPAL.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Byte()).Data), d As __INSPECCIONMUNICIPAL.DetailsClass, sf As Object)
                    c(d, d._RowVersion, sf)
                End Sub
                Private Shared Function _RowVersion_ComputeIsReadOnly(e As __INSPECCIONMUNICIPAL) As Boolean
                    Dim result As Boolean = False
                    e.RowVersion_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _RowVersion_Validate(e As __INSPECCIONMUNICIPAL, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.RowVersion_Validate(r)
                End Sub
                Private Shared Function _RowVersion_GetImplementationValue(d As __INSPECCIONMUNICIPAL.DetailsClass) As Byte()
                    Return d.ImplementationEntity.RowVersion
                End Function
                Private Shared Sub _RowVersion_SetImplementationValue(d As __INSPECCIONMUNICIPAL.DetailsClass, v As Byte())
                    d.ImplementationEntity.RowVersion = v
                End Sub
                Private Shared Sub _RowVersion_OnValueChanged(e As __INSPECCIONMUNICIPAL)
                    e.RowVersion_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly OBRA As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Global.LightSwitchApplication.OBRA).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Global.LightSwitchApplication.OBRA).Entry( _
                        "OBRA", _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._OBRA_Stub, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._OBRA_ComputeIsReadOnly, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._OBRA_Validate, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._OBRA_GetCoreImplementationValue, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._OBRA_GetImplementationValue, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._OBRA_SetImplementationValue, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._OBRA_Refresh, _
                        AddressOf __INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties._OBRA_OnValueChanged)
                Private Shared Sub _OBRA_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __INSPECCIONMUNICIPAL.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Global.LightSwitchApplication.OBRA).Data), d As __INSPECCIONMUNICIPAL.DetailsClass, sf As Object)
                    c(d, d._OBRA, sf)
                End Sub
                Private Shared Function _OBRA_ComputeIsReadOnly(e As __INSPECCIONMUNICIPAL) As Boolean
                    Dim result As Boolean = False
                    e.OBRA_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _OBRA_Validate(e As __INSPECCIONMUNICIPAL, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.OBRA_Validate(r)
                End Sub
                Private Shared Function _OBRA_GetCoreImplementationValue(d as __INSPECCIONMUNICIPAL.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.OBRA
                End Function
                Private Shared Function _OBRA_GetImplementationValue(d as __INSPECCIONMUNICIPAL.DetailsClass) As Global.LightSwitchApplication.OBRA
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.OBRA, Global.LightSwitchApplication.OBRA.DetailsClass)(__INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.OBRA, d._OBRA)
                End Function
                Private Shared Sub _OBRA_SetImplementationValue(d As __INSPECCIONMUNICIPAL.DetailsClass, v As Global.LightSwitchApplication.OBRA)
                    d.SetImplementationValue(__INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.OBRA, d._OBRA, Sub(i, ev) i.OBRA = ev, v)
                End Sub
                Private Shared Sub _OBRA_Refresh(d As __INSPECCIONMUNICIPAL.DetailsClass)
                    d.RefreshNavigationProperty(__INSPECCIONMUNICIPAL.DetailsClass.PropertySetProperties.OBRA, d._OBRA)
                End Sub
                Private Shared Sub _OBRA_OnValueChanged(e As __INSPECCIONMUNICIPAL)
                    e.OBRA_Changed()
                End Sub
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _FECHAREALIZADA As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Date).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ESTADO As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _FECHAESTADO As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Date).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CreatedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Created As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ModifiedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Modified As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Byte()).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _OBRA As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __INSPECCIONMUNICIPAL, __INSPECCIONMUNICIPAL.DetailsClass, Global.LightSwitchApplication.OBRA).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
