
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __AVANCEDEOBRA = LightSwitchApplication.AVANCEDEOBRA

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No hay ninguna descripción modelada
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    Public NotInheritable Partial Class AVANCEDEOBRA
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Inicializa una nueva instancia de la entidad AVANCEDEOBRA.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __AVANCEDEOBRA))
            MyBase.New(entitySet)
            
            __AVANCEDEOBRA.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AVANCEDEOBRA_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub AVANCEDEOBRA_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return TryCast(Global.LightSwitchApplication.Application.Current, Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace))
            End Get
        End Property
        
        ''' <summary>
        ''' Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Id As Integer
            Get
                Return __AVANCEDEOBRA.DetailsClass.GetValue(Me, __AVANCEDEOBRA.DetailsClass.PropertySetProperties.Id)
            End Get
            Set
                __AVANCEDEOBRA.DetailsClass.SetValue(Me, __AVANCEDEOBRA.DetailsClass.PropertySetProperties.Id, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property CATEGORIA As String
            Get
                Return __AVANCEDEOBRA.DetailsClass.GetValue(Me, __AVANCEDEOBRA.DetailsClass.PropertySetProperties.CATEGORIA)
            End Get
            Set
                __AVANCEDEOBRA.DetailsClass.SetValue(Me, __AVANCEDEOBRA.DetailsClass.PropertySetProperties.CATEGORIA, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CATEGORIA_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CATEGORIA_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CATEGORIA_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property TIPODEAVANCE As String
            Get
                Return __AVANCEDEOBRA.DetailsClass.GetValue(Me, __AVANCEDEOBRA.DetailsClass.PropertySetProperties.TIPODEAVANCE)
            End Get
            Set
                __AVANCEDEOBRA.DetailsClass.SetValue(Me, __AVANCEDEOBRA.DetailsClass.PropertySetProperties.TIPODEAVANCE, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub TIPODEAVANCE_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub TIPODEAVANCE_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub TIPODEAVANCE_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property FECHAAVANCE As Date
            Get
                Return __AVANCEDEOBRA.DetailsClass.GetValue(Me, __AVANCEDEOBRA.DetailsClass.PropertySetProperties.FECHAAVANCE)
            End Get
            Set
                __AVANCEDEOBRA.DetailsClass.SetValue(Me, __AVANCEDEOBRA.DetailsClass.PropertySetProperties.FECHAAVANCE, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FECHAAVANCE_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FECHAAVANCE_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FECHAAVANCE_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property FECHAPOSIBLEDEFINALIZACION As Date
            Get
                Return __AVANCEDEOBRA.DetailsClass.GetValue(Me, __AVANCEDEOBRA.DetailsClass.PropertySetProperties.FECHAPOSIBLEDEFINALIZACION)
            End Get
            Set
                __AVANCEDEOBRA.DetailsClass.SetValue(Me, __AVANCEDEOBRA.DetailsClass.PropertySetProperties.FECHAPOSIBLEDEFINALIZACION, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FECHAPOSIBLEDEFINALIZACION_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FECHAPOSIBLEDEFINALIZACION_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FECHAPOSIBLEDEFINALIZACION_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property CreatedBy As String
            Get
                Return __AVANCEDEOBRA.DetailsClass.GetValue(Me, __AVANCEDEOBRA.DetailsClass.PropertySetProperties.CreatedBy)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreatedBy_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreatedBy_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreatedBy_Changed()
        End Sub
        Public ReadOnly Property CreatedByInfo() As Global.Microsoft.LightSwitch.Framework.Server.PersonInfo
            Get
                Dim personInfoFactory As Global.Microsoft.LightSwitch.Server.IPersonInfoFactory = Global.LightSwitchApplication.Application.Current.GetPersonInfoFactory()
                Return DirectCast(personInfoFactory.ResolvePerson(Me.CreatedBy), Global.Microsoft.LightSwitch.Framework.Server.PersonInfo)
            End Get
        End Property

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Created As Global.System.Nullable(Of Global.System.DateTimeOffset)
            Get
                Return __AVANCEDEOBRA.DetailsClass.GetValue(Me, __AVANCEDEOBRA.DetailsClass.PropertySetProperties.Created)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Created_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Created_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Created_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property ModifiedBy As String
            Get
                Return __AVANCEDEOBRA.DetailsClass.GetValue(Me, __AVANCEDEOBRA.DetailsClass.PropertySetProperties.ModifiedBy)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ModifiedBy_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ModifiedBy_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ModifiedBy_Changed()
        End Sub
        Public ReadOnly Property ModifiedByInfo() As Global.Microsoft.LightSwitch.Framework.Server.PersonInfo
            Get
                Dim personInfoFactory As Global.Microsoft.LightSwitch.Server.IPersonInfoFactory = Global.LightSwitchApplication.Application.Current.GetPersonInfoFactory()
                Return DirectCast(personInfoFactory.ResolvePerson(Me.ModifiedBy), Global.Microsoft.LightSwitch.Framework.Server.PersonInfo)
            End Get
        End Property

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Modified As Global.System.Nullable(Of Global.System.DateTimeOffset)
            Get
                Return __AVANCEDEOBRA.DetailsClass.GetValue(Me, __AVANCEDEOBRA.DetailsClass.PropertySetProperties.Modified)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Modified_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Modified_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Modified_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property RowVersion As Byte()
            Get
                Return __AVANCEDEOBRA.DetailsClass.GetValue(Me, __AVANCEDEOBRA.DetailsClass.PropertySetProperties.RowVersion)
            End Get
            Set
                __AVANCEDEOBRA.DetailsClass.SetValue(Me, __AVANCEDEOBRA.DetailsClass.PropertySetProperties.RowVersion, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property CONSTRUCCIONDEOBRA As Global.LightSwitchApplication.CONSTRUCCIONDEOBRA
            Get
                Return __AVANCEDEOBRA.DetailsClass.GetValue(Me, __AVANCEDEOBRA.DetailsClass.PropertySetProperties.CONSTRUCCIONDEOBRA)
            End Get
            Set
                __AVANCEDEOBRA.DetailsClass.SetValue(Me, __AVANCEDEOBRA.DetailsClass.PropertySetProperties.CONSTRUCCIONDEOBRA, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CONSTRUCCIONDEOBRA_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CONSTRUCCIONDEOBRA_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CONSTRUCCIONDEOBRA_Changed()
        End Sub

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __AVANCEDEOBRA, _
                __AVANCEDEOBRA.DetailsClass, _
                __AVANCEDEOBRA.DetailsClass.IImplementation, _
                __AVANCEDEOBRA.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __AVANCEDEOBRA.DetailsClass.PropertySetProperties.Id
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __AVANCEDEOBRAEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass).Entry( _
                    AddressOf __AVANCEDEOBRA.DetailsClass.__AVANCEDEOBRA_CreateNew, _
                    AddressOf __AVANCEDEOBRA.DetailsClass.__AVANCEDEOBRA_Created, _
                    AddressOf __AVANCEDEOBRA.DetailsClass.__AVANCEDEOBRA_AllowSaveWithErrors)
            Private Shared Function __AVANCEDEOBRA_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __AVANCEDEOBRA)) As __AVANCEDEOBRA
                Return New __AVANCEDEOBRA(es)
            End Function
            Private Shared Sub __AVANCEDEOBRA_Created(e As __AVANCEDEOBRA)
                e.AVANCEDEOBRA_Created()
            End Sub
            Private Shared Function __AVANCEDEOBRA_AllowSaveWithErrors(e As __AVANCEDEOBRA) As Boolean
                Dim result As Boolean = False
                e.AVANCEDEOBRA_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __AVANCEDEOBRA.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AVANCEDEOBRA.DetailsClass.PropertySetProperties.Id),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property CATEGORIA As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AVANCEDEOBRA.DetailsClass.PropertySetProperties.CATEGORIA),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property TIPODEAVANCE As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AVANCEDEOBRA.DetailsClass.PropertySetProperties.TIPODEAVANCE),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property FECHAAVANCE As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Date)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AVANCEDEOBRA.DetailsClass.PropertySetProperties.FECHAAVANCE),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Date))
                    End Get
                End Property
                
                Public ReadOnly Property FECHAPOSIBLEDEFINALIZACION As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Date)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AVANCEDEOBRA.DetailsClass.PropertySetProperties.FECHAPOSIBLEDEFINALIZACION),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Date))
                    End Get
                End Property
                
                Public ReadOnly Property CreatedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AVANCEDEOBRA.DetailsClass.PropertySetProperties.CreatedBy),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Created As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AVANCEDEOBRA.DetailsClass.PropertySetProperties.Created),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)))
                    End Get
                End Property
                
                Public ReadOnly Property ModifiedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AVANCEDEOBRA.DetailsClass.PropertySetProperties.ModifiedBy),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Modified As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AVANCEDEOBRA.DetailsClass.PropertySetProperties.Modified),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)))
                    End Get
                End Property
                
                Public ReadOnly Property RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Byte())
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AVANCEDEOBRA.DetailsClass.PropertySetProperties.RowVersion),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Byte()))
                    End Get
                End Property
                
                Public ReadOnly Property CONSTRUCCIONDEOBRA As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__AVANCEDEOBRA.DetailsClass.PropertySetProperties.CONSTRUCCIONDEOBRA),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property Id As Integer
                Shadows Property CATEGORIA As String
                Shadows Property TIPODEAVANCE As String
                Shadows Property FECHAAVANCE As Date
                Shadows Property FECHAPOSIBLEDEFINALIZACION As Date
                Shadows ReadOnly Property CreatedBy As String
                Shadows ReadOnly Property Created As Global.System.Nullable(Of Global.System.DateTimeOffset)
                Shadows ReadOnly Property ModifiedBy As String
                Shadows ReadOnly Property Modified As Global.System.Nullable(Of Global.System.DateTimeOffset)
                Shadows Property RowVersion As Byte()
                Shadows Property CONSTRUCCIONDEOBRA As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Integer).Entry( _
                        "Id", _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._Id_Stub, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._Id_Validate, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._Id_GetImplementationValue, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._Id_SetImplementationValue, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._Id_OnValueChanged)
                Private Shared Sub _Id_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AVANCEDEOBRA.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Integer).Data), d As __AVANCEDEOBRA.DetailsClass, sf As Object)
                    c(d, d._Id, sf)
                End Sub
                Private Shared Function _Id_ComputeIsReadOnly(e As __AVANCEDEOBRA) As Boolean
                    Dim result As Boolean = False
                    e.Id_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Id_Validate(e As __AVANCEDEOBRA, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Id_Validate(r)
                End Sub
                Private Shared Function _Id_GetImplementationValue(d As __AVANCEDEOBRA.DetailsClass) As Integer
                    Return d.ImplementationEntity.Id
                End Function
                Private Shared Sub _Id_SetImplementationValue(d As __AVANCEDEOBRA.DetailsClass, v As Integer)
                    d.ImplementationEntity.Id = v
                End Sub
                Private Shared Sub _Id_OnValueChanged(e As __AVANCEDEOBRA)
                    e.Id_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CATEGORIA As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String).Entry( _
                        "CATEGORIA", _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._CATEGORIA_Stub, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._CATEGORIA_ComputeIsReadOnly, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._CATEGORIA_Validate, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._CATEGORIA_GetImplementationValue, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._CATEGORIA_SetImplementationValue, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._CATEGORIA_OnValueChanged)
                Private Shared Sub _CATEGORIA_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AVANCEDEOBRA.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String).Data), d As __AVANCEDEOBRA.DetailsClass, sf As Object)
                    c(d, d._CATEGORIA, sf)
                End Sub
                Private Shared Function _CATEGORIA_ComputeIsReadOnly(e As __AVANCEDEOBRA) As Boolean
                    Dim result As Boolean = False
                    e.CATEGORIA_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _CATEGORIA_Validate(e As __AVANCEDEOBRA, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.CATEGORIA_Validate(r)
                End Sub
                Private Shared Function _CATEGORIA_GetImplementationValue(d As __AVANCEDEOBRA.DetailsClass) As String
                    Return d.ImplementationEntity.CATEGORIA
                End Function
                Private Shared Sub _CATEGORIA_SetImplementationValue(d As __AVANCEDEOBRA.DetailsClass, v As String)
                    d.ImplementationEntity.CATEGORIA = v
                End Sub
                Private Shared Sub _CATEGORIA_OnValueChanged(e As __AVANCEDEOBRA)
                    e.CATEGORIA_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly TIPODEAVANCE As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String).Entry( _
                        "TIPODEAVANCE", _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._TIPODEAVANCE_Stub, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._TIPODEAVANCE_ComputeIsReadOnly, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._TIPODEAVANCE_Validate, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._TIPODEAVANCE_GetImplementationValue, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._TIPODEAVANCE_SetImplementationValue, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._TIPODEAVANCE_OnValueChanged)
                Private Shared Sub _TIPODEAVANCE_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AVANCEDEOBRA.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String).Data), d As __AVANCEDEOBRA.DetailsClass, sf As Object)
                    c(d, d._TIPODEAVANCE, sf)
                End Sub
                Private Shared Function _TIPODEAVANCE_ComputeIsReadOnly(e As __AVANCEDEOBRA) As Boolean
                    Dim result As Boolean = False
                    e.TIPODEAVANCE_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _TIPODEAVANCE_Validate(e As __AVANCEDEOBRA, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.TIPODEAVANCE_Validate(r)
                End Sub
                Private Shared Function _TIPODEAVANCE_GetImplementationValue(d As __AVANCEDEOBRA.DetailsClass) As String
                    Return d.ImplementationEntity.TIPODEAVANCE
                End Function
                Private Shared Sub _TIPODEAVANCE_SetImplementationValue(d As __AVANCEDEOBRA.DetailsClass, v As String)
                    d.ImplementationEntity.TIPODEAVANCE = v
                End Sub
                Private Shared Sub _TIPODEAVANCE_OnValueChanged(e As __AVANCEDEOBRA)
                    e.TIPODEAVANCE_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly FECHAAVANCE As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Date).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Date).Entry( _
                        "FECHAAVANCE", _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._FECHAAVANCE_Stub, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._FECHAAVANCE_ComputeIsReadOnly, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._FECHAAVANCE_Validate, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._FECHAAVANCE_GetImplementationValue, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._FECHAAVANCE_SetImplementationValue, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._FECHAAVANCE_OnValueChanged)
                Private Shared Sub _FECHAAVANCE_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AVANCEDEOBRA.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Date).Data), d As __AVANCEDEOBRA.DetailsClass, sf As Object)
                    c(d, d._FECHAAVANCE, sf)
                End Sub
                Private Shared Function _FECHAAVANCE_ComputeIsReadOnly(e As __AVANCEDEOBRA) As Boolean
                    Dim result As Boolean = False
                    e.FECHAAVANCE_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _FECHAAVANCE_Validate(e As __AVANCEDEOBRA, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.FECHAAVANCE_Validate(r)
                End Sub
                Private Shared Function _FECHAAVANCE_GetImplementationValue(d As __AVANCEDEOBRA.DetailsClass) As Date
                    Return d.ImplementationEntity.FECHAAVANCE
                End Function
                Private Shared Sub _FECHAAVANCE_SetImplementationValue(d As __AVANCEDEOBRA.DetailsClass, v As Date)
                    d.ImplementationEntity.FECHAAVANCE = __AVANCEDEOBRA.DetailsClass.TruncateDate(v)
                End Sub
                Private Shared Sub _FECHAAVANCE_OnValueChanged(e As __AVANCEDEOBRA)
                    e.FECHAAVANCE_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly FECHAPOSIBLEDEFINALIZACION As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Date).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Date).Entry( _
                        "FECHAPOSIBLEDEFINALIZACION", _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._FECHAPOSIBLEDEFINALIZACION_Stub, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._FECHAPOSIBLEDEFINALIZACION_ComputeIsReadOnly, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._FECHAPOSIBLEDEFINALIZACION_Validate, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._FECHAPOSIBLEDEFINALIZACION_GetImplementationValue, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._FECHAPOSIBLEDEFINALIZACION_SetImplementationValue, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._FECHAPOSIBLEDEFINALIZACION_OnValueChanged)
                Private Shared Sub _FECHAPOSIBLEDEFINALIZACION_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AVANCEDEOBRA.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Date).Data), d As __AVANCEDEOBRA.DetailsClass, sf As Object)
                    c(d, d._FECHAPOSIBLEDEFINALIZACION, sf)
                End Sub
                Private Shared Function _FECHAPOSIBLEDEFINALIZACION_ComputeIsReadOnly(e As __AVANCEDEOBRA) As Boolean
                    Dim result As Boolean = False
                    e.FECHAPOSIBLEDEFINALIZACION_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _FECHAPOSIBLEDEFINALIZACION_Validate(e As __AVANCEDEOBRA, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.FECHAPOSIBLEDEFINALIZACION_Validate(r)
                End Sub
                Private Shared Function _FECHAPOSIBLEDEFINALIZACION_GetImplementationValue(d As __AVANCEDEOBRA.DetailsClass) As Date
                    Return d.ImplementationEntity.FECHAPOSIBLEDEFINALIZACION
                End Function
                Private Shared Sub _FECHAPOSIBLEDEFINALIZACION_SetImplementationValue(d As __AVANCEDEOBRA.DetailsClass, v As Date)
                    d.ImplementationEntity.FECHAPOSIBLEDEFINALIZACION = __AVANCEDEOBRA.DetailsClass.TruncateDate(v)
                End Sub
                Private Shared Sub _FECHAPOSIBLEDEFINALIZACION_OnValueChanged(e As __AVANCEDEOBRA)
                    e.FECHAPOSIBLEDEFINALIZACION_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CreatedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String).Entry( _
                        "CreatedBy", _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._CreatedBy_Stub, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._CreatedBy_Validate, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue, _
                        Nothing, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged)
                Private Shared Sub _CreatedBy_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AVANCEDEOBRA.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String).Data), d As __AVANCEDEOBRA.DetailsClass, sf As Object)
                    c(d, d._CreatedBy, sf)
                End Sub
                Private Shared Function _CreatedBy_ComputeIsReadOnly(e As __AVANCEDEOBRA) As Boolean
                    Dim result As Boolean = False
                    e.CreatedBy_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _CreatedBy_Validate(e As __AVANCEDEOBRA, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.CreatedBy_Validate(r)
                End Sub
                Private Shared Function _CreatedBy_GetImplementationValue(d As __AVANCEDEOBRA.DetailsClass) As String
                    Return d.ImplementationEntity.CreatedBy
                End Function
                Private Shared Sub _CreatedBy_OnValueChanged(e As __AVANCEDEOBRA)
                    e.CreatedBy_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Created As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry( _
                        "Created", _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._Created_Stub, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._Created_Validate, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._Created_GetImplementationValue, _
                        Nothing, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._Created_OnValueChanged)
                Private Shared Sub _Created_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AVANCEDEOBRA.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data), d As __AVANCEDEOBRA.DetailsClass, sf As Object)
                    c(d, d._Created, sf)
                End Sub
                Private Shared Function _Created_ComputeIsReadOnly(e As __AVANCEDEOBRA) As Boolean
                    Dim result As Boolean = False
                    e.Created_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Created_Validate(e As __AVANCEDEOBRA, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Created_Validate(r)
                End Sub
                Private Shared Function _Created_GetImplementationValue(d As __AVANCEDEOBRA.DetailsClass) As Global.System.Nullable(Of Global.System.DateTimeOffset)
                    Return d.ImplementationEntity.Created
                End Function
                Private Shared Sub _Created_OnValueChanged(e As __AVANCEDEOBRA)
                    e.Created_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ModifiedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String).Entry( _
                        "ModifiedBy", _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._ModifiedBy_Stub, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._ModifiedBy_Validate, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue, _
                        Nothing, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged)
                Private Shared Sub _ModifiedBy_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AVANCEDEOBRA.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String).Data), d As __AVANCEDEOBRA.DetailsClass, sf As Object)
                    c(d, d._ModifiedBy, sf)
                End Sub
                Private Shared Function _ModifiedBy_ComputeIsReadOnly(e As __AVANCEDEOBRA) As Boolean
                    Dim result As Boolean = False
                    e.ModifiedBy_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ModifiedBy_Validate(e As __AVANCEDEOBRA, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ModifiedBy_Validate(r)
                End Sub
                Private Shared Function _ModifiedBy_GetImplementationValue(d As __AVANCEDEOBRA.DetailsClass) As String
                    Return d.ImplementationEntity.ModifiedBy
                End Function
                Private Shared Sub _ModifiedBy_OnValueChanged(e As __AVANCEDEOBRA)
                    e.ModifiedBy_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Modified As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry( _
                        "Modified", _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._Modified_Stub, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._Modified_Validate, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._Modified_GetImplementationValue, _
                        Nothing, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._Modified_OnValueChanged)
                Private Shared Sub _Modified_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AVANCEDEOBRA.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data), d As __AVANCEDEOBRA.DetailsClass, sf As Object)
                    c(d, d._Modified, sf)
                End Sub
                Private Shared Function _Modified_ComputeIsReadOnly(e As __AVANCEDEOBRA) As Boolean
                    Dim result As Boolean = False
                    e.Modified_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Modified_Validate(e As __AVANCEDEOBRA, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Modified_Validate(r)
                End Sub
                Private Shared Function _Modified_GetImplementationValue(d As __AVANCEDEOBRA.DetailsClass) As Global.System.Nullable(Of Global.System.DateTimeOffset)
                    Return d.ImplementationEntity.Modified
                End Function
                Private Shared Sub _Modified_OnValueChanged(e As __AVANCEDEOBRA)
                    e.Modified_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Byte()).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Byte()).Entry( _
                        "RowVersion", _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._RowVersion_Stub, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._RowVersion_Validate, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged)
                Private Shared Sub _RowVersion_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AVANCEDEOBRA.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Byte()).Data), d As __AVANCEDEOBRA.DetailsClass, sf As Object)
                    c(d, d._RowVersion, sf)
                End Sub
                Private Shared Function _RowVersion_ComputeIsReadOnly(e As __AVANCEDEOBRA) As Boolean
                    Dim result As Boolean = False
                    e.RowVersion_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _RowVersion_Validate(e As __AVANCEDEOBRA, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.RowVersion_Validate(r)
                End Sub
                Private Shared Function _RowVersion_GetImplementationValue(d As __AVANCEDEOBRA.DetailsClass) As Byte()
                    Return d.ImplementationEntity.RowVersion
                End Function
                Private Shared Sub _RowVersion_SetImplementationValue(d As __AVANCEDEOBRA.DetailsClass, v As Byte())
                    d.ImplementationEntity.RowVersion = v
                End Sub
                Private Shared Sub _RowVersion_OnValueChanged(e As __AVANCEDEOBRA)
                    e.RowVersion_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CONSTRUCCIONDEOBRA As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA).Entry( _
                        "CONSTRUCCIONDEOBRA", _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._CONSTRUCCIONDEOBRA_Stub, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._CONSTRUCCIONDEOBRA_ComputeIsReadOnly, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._CONSTRUCCIONDEOBRA_Validate, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._CONSTRUCCIONDEOBRA_GetCoreImplementationValue, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._CONSTRUCCIONDEOBRA_GetImplementationValue, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._CONSTRUCCIONDEOBRA_SetImplementationValue, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._CONSTRUCCIONDEOBRA_Refresh, _
                        AddressOf __AVANCEDEOBRA.DetailsClass.PropertySetProperties._CONSTRUCCIONDEOBRA_OnValueChanged)
                Private Shared Sub _CONSTRUCCIONDEOBRA_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __AVANCEDEOBRA.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA).Data), d As __AVANCEDEOBRA.DetailsClass, sf As Object)
                    c(d, d._CONSTRUCCIONDEOBRA, sf)
                End Sub
                Private Shared Function _CONSTRUCCIONDEOBRA_ComputeIsReadOnly(e As __AVANCEDEOBRA) As Boolean
                    Dim result As Boolean = False
                    e.CONSTRUCCIONDEOBRA_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _CONSTRUCCIONDEOBRA_Validate(e As __AVANCEDEOBRA, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.CONSTRUCCIONDEOBRA_Validate(r)
                End Sub
                Private Shared Function _CONSTRUCCIONDEOBRA_GetCoreImplementationValue(d as __AVANCEDEOBRA.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.CONSTRUCCIONDEOBRA
                End Function
                Private Shared Function _CONSTRUCCIONDEOBRA_GetImplementationValue(d as __AVANCEDEOBRA.DetailsClass) As Global.LightSwitchApplication.CONSTRUCCIONDEOBRA
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.CONSTRUCCIONDEOBRA, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass)(__AVANCEDEOBRA.DetailsClass.PropertySetProperties.CONSTRUCCIONDEOBRA, d._CONSTRUCCIONDEOBRA)
                End Function
                Private Shared Sub _CONSTRUCCIONDEOBRA_SetImplementationValue(d As __AVANCEDEOBRA.DetailsClass, v As Global.LightSwitchApplication.CONSTRUCCIONDEOBRA)
                    d.SetImplementationValue(__AVANCEDEOBRA.DetailsClass.PropertySetProperties.CONSTRUCCIONDEOBRA, d._CONSTRUCCIONDEOBRA, Sub(i, ev) i.CONSTRUCCIONDEOBRA = ev, v)
                End Sub
                Private Shared Sub _CONSTRUCCIONDEOBRA_Refresh(d As __AVANCEDEOBRA.DetailsClass)
                    d.RefreshNavigationProperty(__AVANCEDEOBRA.DetailsClass.PropertySetProperties.CONSTRUCCIONDEOBRA, d._CONSTRUCCIONDEOBRA)
                End Sub
                Private Shared Sub _CONSTRUCCIONDEOBRA_OnValueChanged(e As __AVANCEDEOBRA)
                    e.CONSTRUCCIONDEOBRA_Changed()
                End Sub
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CATEGORIA As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _TIPODEAVANCE As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _FECHAAVANCE As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Date).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _FECHAPOSIBLEDEFINALIZACION As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Date).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CreatedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Created As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ModifiedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Modified As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Byte()).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CONSTRUCCIONDEOBRA As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __AVANCEDEOBRA, __AVANCEDEOBRA.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
