
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace LightSwitchApplication

    #Region "Data Workspace"
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public NotInheritable Class DataWorkspace
        Inherits Global.Microsoft.LightSwitch.Framework.Base.DataWorkspace(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Inicializa una nueva instancia de un elemento DataWorkspace. En esta nueva instancia, los orígenes de datos pueden modificarse con independencia de los cambios realizados en los orígenes de datos del elemento DataWorkspace predeterminado.
        ''' </summary>
        Public Sub New()
            MyBase.New()
        End Sub
    
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' Obtiene el origen de datos ApplicationData. Este proporciona miembros para consultar y actualizar datos en el origen de datos.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property ApplicationData As Global.LightSwitchApplication.ApplicationData
            Get
                Return Global.LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(Me, Global.LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData)
            End Get
        End Property
        
        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.DataWorkspaceDetails(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet)
    
            Shared Sub New()
                Dim initializeEntry = Global.LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData
            End Sub
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Properties As Global.LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.DataWorkspacePropertySet(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property ApplicationData As Global.Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.ApplicationData)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ApplicationData),
                            Global.Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.ApplicationData))
                    End Get
                End Property
                
            End Class
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ApplicationData As Global.Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.ApplicationData).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.ApplicationData).Entry( _
                        "ApplicationData", _
                        AddressOf Global.LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._ApplicationData_Stub)
                Private Shared Sub _ApplicationData_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.ApplicationData).Data), d As Global.LightSwitchApplication.DataWorkspace.DetailsClass, sf As Object)
                    c(d, d._ApplicationData, sf)
                End Sub
                 
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ApplicationData As Global.Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty(Of Global.LightSwitchApplication.DataWorkspace, Global.LightSwitchApplication.DataWorkspace.DetailsClass, Global.LightSwitchApplication.ApplicationData).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
    
    #Region "Data Services"
    
    ''' <summary>
    ''' Proporciona miembros para consultar y actualizar datos en el origen de datos ApplicationData.
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class ApplicationData
        Inherits Global.Microsoft.LightSwitch.Framework.Base.DataService(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Este constructor se usa para el marco interno de LightSwitch. Use DataWorkspace en su lugar.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)>
        Public Sub New()
            MyBase.New()
        End Sub
    
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' Obtiene el conjunto de entidades AVANCEDEOBRAs. El conjunto de entidades proporciona miembros para obtener acceso a las entidades de un tipo específico.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property AVANCEDEOBRAs As Global.Microsoft.LightSwitch.Framework.EntitySet(Of Global.LightSwitchApplication.AVANCEDEOBRA)
            Get
                Return Global.LightSwitchApplication.ApplicationData.DetailsClass.GetValue(Me, Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.AVANCEDEOBRAs)
            End Get
        End Property
        
        ''' <summary>
        ''' Obtiene el conjunto de entidades CONSTRUCCIONDEOBRAs. El conjunto de entidades proporciona miembros para obtener acceso a las entidades de un tipo específico.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property CONSTRUCCIONDEOBRAs As Global.Microsoft.LightSwitch.Framework.EntitySet(Of Global.LightSwitchApplication.CONSTRUCCIONDEOBRA)
            Get
                Return Global.LightSwitchApplication.ApplicationData.DetailsClass.GetValue(Me, Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.CONSTRUCCIONDEOBRAs)
            End Get
        End Property
        
        ''' <summary>
        ''' Obtiene el conjunto de entidades INSPECCIONMUNICIPALs. El conjunto de entidades proporciona miembros para obtener acceso a las entidades de un tipo específico.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property INSPECCIONMUNICIPALs As Global.Microsoft.LightSwitch.Framework.EntitySet(Of Global.LightSwitchApplication.INSPECCIONMUNICIPAL)
            Get
                Return Global.LightSwitchApplication.ApplicationData.DetailsClass.GetValue(Me, Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.INSPECCIONMUNICIPALs)
            End Get
        End Property
        
        ''' <summary>
        ''' Obtiene el conjunto de entidades INSPECCIONs. El conjunto de entidades proporciona miembros para obtener acceso a las entidades de un tipo específico.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property INSPECCIONs As Global.Microsoft.LightSwitch.Framework.EntitySet(Of Global.LightSwitchApplication.INSPECCION)
            Get
                Return Global.LightSwitchApplication.ApplicationData.DetailsClass.GetValue(Me, Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.INSPECCIONs)
            End Get
        End Property
        
        ''' <summary>
        ''' Obtiene el conjunto de entidades OBRAs. El conjunto de entidades proporciona miembros para obtener acceso a las entidades de un tipo específico.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property OBRAs As Global.Microsoft.LightSwitch.Framework.EntitySet(Of Global.LightSwitchApplication.OBRA)
            Get
                Return Global.LightSwitchApplication.ApplicationData.DetailsClass.GetValue(Me, Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.OBRAs)
            End Get
        End Property
        
        ''' <summary>
        ''' Obtiene el conjunto de entidades PERMISOSSet. El conjunto de entidades proporciona miembros para obtener acceso a las entidades de un tipo específico.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property PERMISOSSet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of Global.LightSwitchApplication.PERMISOS)
            Get
                Return Global.LightSwitchApplication.ApplicationData.DetailsClass.GetValue(Me, Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.PERMISOSSet)
            End Get
        End Property
        
        ''' <summary>
        ''' Obtiene el conjunto de entidades PLANOes. El conjunto de entidades proporciona miembros para obtener acceso a las entidades de un tipo específico.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property PLANOes As Global.Microsoft.LightSwitch.Framework.EntitySet(Of Global.LightSwitchApplication.PLANO)
            Get
                Return Global.LightSwitchApplication.ApplicationData.DetailsClass.GetValue(Me, Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.PLANOes)
            End Get
        End Property
        
        #End Region
    
        #Region "Queries"
    
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s).
        ''' </summary>
        ''' <param name="Id">
        ''' The value of the 'Id' key property of the entity to retrieve.
        ''' </param>
        Public Function AVANCEDEOBRAs_Single(ByVal Id As Global.System.Nullable(Of Integer)) As Global.LightSwitchApplication.AVANCEDEOBRA
            Return Me.Details.Methods.AVANCEDEOBRAs_Single.CreateInvocation(Id).Execute()
        End Function
        
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        ''' </summary>
        ''' <param name="Id">
        ''' The value of the 'Id' key property of the entity to retrieve.
        ''' </param>
        Public Function AVANCEDEOBRAs_SingleOrDefault(ByVal Id As Global.System.Nullable(Of Integer)) As Global.LightSwitchApplication.AVANCEDEOBRA
            Return Me.Details.Methods.AVANCEDEOBRAs_SingleOrDefault.CreateInvocation(Id).Execute()
        End Function
        
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s).
        ''' </summary>
        ''' <param name="Id">
        ''' The value of the 'Id' key property of the entity to retrieve.
        ''' </param>
        Public Function CONSTRUCCIONDEOBRAs_Single(ByVal Id As Global.System.Nullable(Of Integer)) As Global.LightSwitchApplication.CONSTRUCCIONDEOBRA
            Return Me.Details.Methods.CONSTRUCCIONDEOBRAs_Single.CreateInvocation(Id).Execute()
        End Function
        
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        ''' </summary>
        ''' <param name="Id">
        ''' The value of the 'Id' key property of the entity to retrieve.
        ''' </param>
        Public Function CONSTRUCCIONDEOBRAs_SingleOrDefault(ByVal Id As Global.System.Nullable(Of Integer)) As Global.LightSwitchApplication.CONSTRUCCIONDEOBRA
            Return Me.Details.Methods.CONSTRUCCIONDEOBRAs_SingleOrDefault.CreateInvocation(Id).Execute()
        End Function
        
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s).
        ''' </summary>
        ''' <param name="Id">
        ''' The value of the 'Id' key property of the entity to retrieve.
        ''' </param>
        Public Function INSPECCIONMUNICIPALs_Single(ByVal Id As Global.System.Nullable(Of Integer)) As Global.LightSwitchApplication.INSPECCIONMUNICIPAL
            Return Me.Details.Methods.INSPECCIONMUNICIPALs_Single.CreateInvocation(Id).Execute()
        End Function
        
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        ''' </summary>
        ''' <param name="Id">
        ''' The value of the 'Id' key property of the entity to retrieve.
        ''' </param>
        Public Function INSPECCIONMUNICIPALs_SingleOrDefault(ByVal Id As Global.System.Nullable(Of Integer)) As Global.LightSwitchApplication.INSPECCIONMUNICIPAL
            Return Me.Details.Methods.INSPECCIONMUNICIPALs_SingleOrDefault.CreateInvocation(Id).Execute()
        End Function
        
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s).
        ''' </summary>
        ''' <param name="Id">
        ''' The value of the 'Id' key property of the entity to retrieve.
        ''' </param>
        Public Function INSPECCIONs_Single(ByVal Id As Global.System.Nullable(Of Integer)) As Global.LightSwitchApplication.INSPECCION
            Return Me.Details.Methods.INSPECCIONs_Single.CreateInvocation(Id).Execute()
        End Function
        
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        ''' </summary>
        ''' <param name="Id">
        ''' The value of the 'Id' key property of the entity to retrieve.
        ''' </param>
        Public Function INSPECCIONs_SingleOrDefault(ByVal Id As Global.System.Nullable(Of Integer)) As Global.LightSwitchApplication.INSPECCION
            Return Me.Details.Methods.INSPECCIONs_SingleOrDefault.CreateInvocation(Id).Execute()
        End Function
        
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s).
        ''' </summary>
        ''' <param name="Id">
        ''' The value of the 'Id' key property of the entity to retrieve.
        ''' </param>
        Public Function OBRAs_Single(ByVal Id As Global.System.Nullable(Of Integer)) As Global.LightSwitchApplication.OBRA
            Return Me.Details.Methods.OBRAs_Single.CreateInvocation(Id).Execute()
        End Function
        
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        ''' </summary>
        ''' <param name="Id">
        ''' The value of the 'Id' key property of the entity to retrieve.
        ''' </param>
        Public Function OBRAs_SingleOrDefault(ByVal Id As Global.System.Nullable(Of Integer)) As Global.LightSwitchApplication.OBRA
            Return Me.Details.Methods.OBRAs_SingleOrDefault.CreateInvocation(Id).Execute()
        End Function
        
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s).
        ''' </summary>
        ''' <param name="Id">
        ''' The value of the 'Id' key property of the entity to retrieve.
        ''' </param>
        Public Function PERMISOSSet_Single(ByVal Id As Global.System.Nullable(Of Integer)) As Global.LightSwitchApplication.PERMISOS
            Return Me.Details.Methods.PERMISOSSet_Single.CreateInvocation(Id).Execute()
        End Function
        
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        ''' </summary>
        ''' <param name="Id">
        ''' The value of the 'Id' key property of the entity to retrieve.
        ''' </param>
        Public Function PERMISOSSet_SingleOrDefault(ByVal Id As Global.System.Nullable(Of Integer)) As Global.LightSwitchApplication.PERMISOS
            Return Me.Details.Methods.PERMISOSSet_SingleOrDefault.CreateInvocation(Id).Execute()
        End Function
        
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s).
        ''' </summary>
        ''' <param name="Id">
        ''' The value of the 'Id' key property of the entity to retrieve.
        ''' </param>
        Public Function PLANOes_Single(ByVal Id As Global.System.Nullable(Of Integer)) As Global.LightSwitchApplication.PLANO
            Return Me.Details.Methods.PLANOes_Single.CreateInvocation(Id).Execute()
        End Function
        
        ''' <summary>
        ''' Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        ''' </summary>
        ''' <param name="Id">
        ''' The value of the 'Id' key property of the entity to retrieve.
        ''' </param>
        Public Function PLANOes_SingleOrDefault(ByVal Id As Global.System.Nullable(Of Integer)) As Global.LightSwitchApplication.PLANO
            Return Me.Details.Methods.PLANOes_SingleOrDefault.CreateInvocation(Id).Execute()
        End Function
        
        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySet, Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSet)
    
            Shared Sub New()
                Dim initializeMethodEntry = Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.AVANCEDEOBRAs_Single
                Dim initializePropertyEntry = Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.AVANCEDEOBRAs
            End Sub
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Methods As Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSet
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class MethodSet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property AVANCEDEOBRAs_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.AVANCEDEOBRA)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.AVANCEDEOBRAs_Single),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.AVANCEDEOBRA))
                    End Get
                End Property
                
                Public ReadOnly Property AVANCEDEOBRAs_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.AVANCEDEOBRA)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.AVANCEDEOBRAs_SingleOrDefault),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.AVANCEDEOBRA))
                    End Get
                End Property
                
                Public ReadOnly Property CONSTRUCCIONDEOBRAs_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.CONSTRUCCIONDEOBRAs_Single),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA))
                    End Get
                End Property
                
                Public ReadOnly Property CONSTRUCCIONDEOBRAs_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.CONSTRUCCIONDEOBRAs_SingleOrDefault),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA))
                    End Get
                End Property
                
                Public ReadOnly Property INSPECCIONMUNICIPALs_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCIONMUNICIPAL)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.INSPECCIONMUNICIPALs_Single),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCIONMUNICIPAL))
                    End Get
                End Property
                
                Public ReadOnly Property INSPECCIONMUNICIPALs_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCIONMUNICIPAL)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.INSPECCIONMUNICIPALs_SingleOrDefault),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCIONMUNICIPAL))
                    End Get
                End Property
                
                Public ReadOnly Property INSPECCIONs_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCION)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.INSPECCIONs_Single),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCION))
                    End Get
                End Property
                
                Public ReadOnly Property INSPECCIONs_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCION)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.INSPECCIONs_SingleOrDefault),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCION))
                    End Get
                End Property
                
                Public ReadOnly Property OBRAs_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.OBRA)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.OBRAs_Single),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.OBRA))
                    End Get
                End Property
                
                Public ReadOnly Property OBRAs_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.OBRA)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.OBRAs_SingleOrDefault),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.OBRA))
                    End Get
                End Property
                
                Public ReadOnly Property PERMISOSSet_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PERMISOS)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.PERMISOSSet_Single),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PERMISOS))
                    End Get
                End Property
                
                Public ReadOnly Property PERMISOSSet_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PERMISOS)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.PERMISOSSet_SingleOrDefault),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PERMISOS))
                    End Get
                End Property
                
                Public ReadOnly Property PLANOes_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PLANO)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.PLANOes_Single),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PLANO))
                    End Get
                End Property
                
                Public ReadOnly Property PLANOes_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PLANO)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties.PLANOes_SingleOrDefault),
                            Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PLANO))
                    End Get
                End Property
                
            End Class
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property AVANCEDEOBRAs As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.AVANCEDEOBRA)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.AVANCEDEOBRAs),
                            Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.AVANCEDEOBRA))
                    End Get
                End Property
                
                Public ReadOnly Property CONSTRUCCIONDEOBRAs As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.CONSTRUCCIONDEOBRAs),
                            Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA))
                    End Get
                End Property
                
                Public ReadOnly Property INSPECCIONMUNICIPALs As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCIONMUNICIPAL)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.INSPECCIONMUNICIPALs),
                            Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCIONMUNICIPAL))
                    End Get
                End Property
                
                Public ReadOnly Property INSPECCIONs As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCION)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.INSPECCIONs),
                            Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCION))
                    End Get
                End Property
                
                Public ReadOnly Property OBRAs As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.OBRA)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.OBRAs),
                            Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.OBRA))
                    End Get
                End Property
                
                Public ReadOnly Property PERMISOSSet As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PERMISOS)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.PERMISOSSet),
                            Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PERMISOS))
                    End Get
                End Property
                
                Public ReadOnly Property PLANOes As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PLANO)
                    Get
                        Return TryCast(
                            MyBase.GetItem(Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties.PLANOes),
                            Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PLANO))
                    End Get
                End Property
                
            End Class
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class MethodSetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly AVANCEDEOBRAs_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.AVANCEDEOBRA).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.AVANCEDEOBRA).Entry( _
                        "AVANCEDEOBRAs_Single", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._AVANCEDEOBRAs_Single_Stub)
                Private Shared Sub _AVANCEDEOBRAs_Single_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.AVANCEDEOBRA).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._AVANCEDEOBRAs_Single, sf)
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly AVANCEDEOBRAs_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.AVANCEDEOBRA).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.AVANCEDEOBRA).Entry( _
                        "AVANCEDEOBRAs_SingleOrDefault", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._AVANCEDEOBRAs_SingleOrDefault_Stub)
                Private Shared Sub _AVANCEDEOBRAs_SingleOrDefault_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.AVANCEDEOBRA).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._AVANCEDEOBRAs_SingleOrDefault, sf)
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CONSTRUCCIONDEOBRAs_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA).Entry( _
                        "CONSTRUCCIONDEOBRAs_Single", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._CONSTRUCCIONDEOBRAs_Single_Stub)
                Private Shared Sub _CONSTRUCCIONDEOBRAs_Single_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._CONSTRUCCIONDEOBRAs_Single, sf)
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CONSTRUCCIONDEOBRAs_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA).Entry( _
                        "CONSTRUCCIONDEOBRAs_SingleOrDefault", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._CONSTRUCCIONDEOBRAs_SingleOrDefault_Stub)
                Private Shared Sub _CONSTRUCCIONDEOBRAs_SingleOrDefault_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._CONSTRUCCIONDEOBRAs_SingleOrDefault, sf)
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly INSPECCIONMUNICIPALs_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCIONMUNICIPAL).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCIONMUNICIPAL).Entry( _
                        "INSPECCIONMUNICIPALs_Single", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._INSPECCIONMUNICIPALs_Single_Stub)
                Private Shared Sub _INSPECCIONMUNICIPALs_Single_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCIONMUNICIPAL).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._INSPECCIONMUNICIPALs_Single, sf)
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly INSPECCIONMUNICIPALs_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCIONMUNICIPAL).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCIONMUNICIPAL).Entry( _
                        "INSPECCIONMUNICIPALs_SingleOrDefault", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._INSPECCIONMUNICIPALs_SingleOrDefault_Stub)
                Private Shared Sub _INSPECCIONMUNICIPALs_SingleOrDefault_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCIONMUNICIPAL).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._INSPECCIONMUNICIPALs_SingleOrDefault, sf)
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly INSPECCIONs_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCION).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCION).Entry( _
                        "INSPECCIONs_Single", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._INSPECCIONs_Single_Stub)
                Private Shared Sub _INSPECCIONs_Single_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCION).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._INSPECCIONs_Single, sf)
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly INSPECCIONs_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCION).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCION).Entry( _
                        "INSPECCIONs_SingleOrDefault", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._INSPECCIONs_SingleOrDefault_Stub)
                Private Shared Sub _INSPECCIONs_SingleOrDefault_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCION).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._INSPECCIONs_SingleOrDefault, sf)
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly OBRAs_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.OBRA).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.OBRA).Entry( _
                        "OBRAs_Single", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._OBRAs_Single_Stub)
                Private Shared Sub _OBRAs_Single_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.OBRA).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._OBRAs_Single, sf)
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly OBRAs_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.OBRA).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.OBRA).Entry( _
                        "OBRAs_SingleOrDefault", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._OBRAs_SingleOrDefault_Stub)
                Private Shared Sub _OBRAs_SingleOrDefault_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.OBRA).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._OBRAs_SingleOrDefault, sf)
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly PERMISOSSet_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PERMISOS).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PERMISOS).Entry( _
                        "PERMISOSSet_Single", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._PERMISOSSet_Single_Stub)
                Private Shared Sub _PERMISOSSet_Single_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PERMISOS).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._PERMISOSSet_Single, sf)
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly PERMISOSSet_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PERMISOS).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PERMISOS).Entry( _
                        "PERMISOSSet_SingleOrDefault", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._PERMISOSSet_SingleOrDefault_Stub)
                Private Shared Sub _PERMISOSSet_SingleOrDefault_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PERMISOS).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._PERMISOSSet_SingleOrDefault, sf)
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly PLANOes_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PLANO).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PLANO).Entry( _
                        "PLANOes_Single", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._PLANOes_Single_Stub)
                Private Shared Sub _PLANOes_Single_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PLANO).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._PLANOes_Single, sf)
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly PLANOes_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PLANO).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PLANO).Entry( _
                        "PLANOes_SingleOrDefault", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.MethodSetProperties._PLANOes_SingleOrDefault_Stub)
                Private Shared Sub _PLANOes_SingleOrDefault_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PLANO).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._PLANOes_SingleOrDefault, sf)
                End Sub
    
            End Class
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly AVANCEDEOBRAs As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.AVANCEDEOBRA).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.AVANCEDEOBRA).Entry( _
                        "AVANCEDEOBRAs", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties._AVANCEDEOBRAs_Stub)
                Private Shared Sub _AVANCEDEOBRAs_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.AVANCEDEOBRA).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._AVANCEDEOBRAs, sf)
                End Sub
     
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CONSTRUCCIONDEOBRAs As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA).Entry( _
                        "CONSTRUCCIONDEOBRAs", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties._CONSTRUCCIONDEOBRAs_Stub)
                Private Shared Sub _CONSTRUCCIONDEOBRAs_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._CONSTRUCCIONDEOBRAs, sf)
                End Sub
     
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly INSPECCIONMUNICIPALs As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCIONMUNICIPAL).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCIONMUNICIPAL).Entry( _
                        "INSPECCIONMUNICIPALs", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties._INSPECCIONMUNICIPALs_Stub)
                Private Shared Sub _INSPECCIONMUNICIPALs_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCIONMUNICIPAL).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._INSPECCIONMUNICIPALs, sf)
                End Sub
     
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly INSPECCIONs As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCION).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCION).Entry( _
                        "INSPECCIONs", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties._INSPECCIONs_Stub)
                Private Shared Sub _INSPECCIONs_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCION).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._INSPECCIONs, sf)
                End Sub
     
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly OBRAs As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.OBRA).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.OBRA).Entry( _
                        "OBRAs", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties._OBRAs_Stub)
                Private Shared Sub _OBRAs_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.OBRA).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._OBRAs, sf)
                End Sub
     
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly PERMISOSSet As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PERMISOS).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PERMISOS).Entry( _
                        "PERMISOSSet", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties._PERMISOSSet_Stub)
                Private Shared Sub _PERMISOSSet_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PERMISOS).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._PERMISOSSet, sf)
                End Sub
     
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly PLANOes As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PLANO).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PLANO).Entry( _
                        "PLANOes", _
                        AddressOf Global.LightSwitchApplication.ApplicationData.DetailsClass.PropertySetProperties._PLANOes_Stub)
                Private Shared Sub _PLANOes_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PLANO).Data), d As Global.LightSwitchApplication.ApplicationData.DetailsClass, sf As Object)
                    c(d, d._PLANOes, sf)
                End Sub
     
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _AVANCEDEOBRAs As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.AVANCEDEOBRA).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CONSTRUCCIONDEOBRAs As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _INSPECCIONMUNICIPALs As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCIONMUNICIPAL).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _INSPECCIONs As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCION).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _OBRAs As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.OBRA).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _PERMISOSSet As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PERMISOS).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _PLANOes As Global.Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PLANO).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _AVANCEDEOBRAs_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.AVANCEDEOBRA).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _AVANCEDEOBRAs_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.AVANCEDEOBRA).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CONSTRUCCIONDEOBRAs_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CONSTRUCCIONDEOBRAs_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.CONSTRUCCIONDEOBRA).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _INSPECCIONMUNICIPALs_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCIONMUNICIPAL).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _INSPECCIONMUNICIPALs_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCIONMUNICIPAL).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _INSPECCIONs_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCION).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _INSPECCIONs_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.INSPECCION).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _OBRAs_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.OBRA).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _OBRAs_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.OBRA).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _PERMISOSSet_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PERMISOS).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _PERMISOSSet_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PERMISOS).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _PLANOes_Single As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PLANO).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _PLANOes_SingleOrDefault As Global.Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod(Of Global.LightSwitchApplication.ApplicationData, Global.LightSwitchApplication.ApplicationData.DetailsClass, Global.LightSwitchApplication.PLANO).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
    
End Namespace
