'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace LightSwitchApplication.Implementation
    
    #Region "AVANCEDEOBRA"
    <Global.System.Runtime.Serialization.DataContract(Namespace:="http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class AVANCEDEOBRA
        Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation
        Private Sub OnAVANCEDEOBRA_CONSTRUCCIONDEOBRAChanged()
            Me.___OnPropertyChanged("AVANCEDEOBRA_CONSTRUCCIONDEOBRA")
            Me.___OnPropertyChanged("CONSTRUCCIONDEOBRA")
        End Sub
        
        Private Property _IdImplementation() As Integer Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.Id
            Get
                Return Me.Id
            End Get
            Set(ByVal value As Integer)
                Me.Id = value
            End Set
        End Property
        
        Private Sub OnIdChanged()
            Me.___OnPropertyChanged("Id")
        End Sub
        
        Private Property _CATEGORIAImplementation() As String Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.CATEGORIA
            Get
                Return Me.CATEGORIA
            End Get
            Set(ByVal value As String)
                Me.CATEGORIA = value
            End Set
        End Property
        
        Private Sub OnCATEGORIAChanged()
            Me.___OnPropertyChanged("CATEGORIA")
        End Sub
        
        Private Property _TIPODEAVANCEImplementation() As String Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.TIPODEAVANCE
            Get
                Return Me.TIPODEAVANCE
            End Get
            Set(ByVal value As String)
                Me.TIPODEAVANCE = value
            End Set
        End Property
        
        Private Sub OnTIPODEAVANCEChanged()
            Me.___OnPropertyChanged("TIPODEAVANCE")
        End Sub
        
        Private Property _FECHAAVANCEImplementation() As Date Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.FECHAAVANCE
            Get
                Return Me.FECHAAVANCE
            End Get
            Set(ByVal value As Date)
                Me.FECHAAVANCE = value
            End Set
        End Property
        
        Private Sub OnFECHAAVANCEChanged()
            Me.___OnPropertyChanged("FECHAAVANCE")
        End Sub
        
        Private Property _FECHAPOSIBLEDEFINALIZACIONImplementation() As Date Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.FECHAPOSIBLEDEFINALIZACION
            Get
                Return Me.FECHAPOSIBLEDEFINALIZACION
            End Get
            Set(ByVal value As Date)
                Me.FECHAPOSIBLEDEFINALIZACION = value
            End Set
        End Property
        
        Private Sub OnFECHAPOSIBLEDEFINALIZACIONChanged()
            Me.___OnPropertyChanged("FECHAPOSIBLEDEFINALIZACION")
        End Sub
        
        Private ReadOnly Property _CreatedByImplementation() As String Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.CreatedBy
            Get
                Return Me.CreatedBy
            End Get
        End Property
        
        Private Sub OnCreatedByChanged()
            Me.___OnPropertyChanged("CreatedBy")
        End Sub
        
        Private ReadOnly Property _CreatedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.Created
            Get
                Return Me.Created
            End Get
        End Property
        
        Private Sub OnCreatedChanged()
            Me.___OnPropertyChanged("Created")
        End Sub
        
        Private ReadOnly Property _ModifiedByImplementation() As String Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.ModifiedBy
            Get
                Return Me.ModifiedBy
            End Get
        End Property
        
        Private Sub OnModifiedByChanged()
            Me.___OnPropertyChanged("ModifiedBy")
        End Sub
        
        Private ReadOnly Property _ModifiedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.Modified
            Get
                Return Me.Modified
            End Get
        End Property
        
        Private Sub OnModifiedChanged()
            Me.___OnPropertyChanged("Modified")
        End Sub
        
        Private Property _RowVersionImplementation() As Byte() Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.RowVersion
            Get
                Return Me.RowVersion
            End Get
            Set(ByVal value As Byte())
                Me.RowVersion = value
            End Set
        End Property
        
        Private Sub OnRowVersionChanged()
            Me.___OnPropertyChanged("RowVersion")
        End Sub
        
        Private Property _CONSTRUCCIONDEOBRAImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.AVANCEDEOBRA.DetailsClass.IImplementation.CONSTRUCCIONDEOBRA
            Get
                Return Me.CONSTRUCCIONDEOBRA
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.CONSTRUCCIONDEOBRA = DirectCast(value, Global.LightSwitchApplication.Implementation.CONSTRUCCIONDEOBRA)
            End Set
        End Property
        
        Private ReadOnly Property __CONSTRUCCIONDEOBRA As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.CONSTRUCCIONDEOBRA) 
            Get
                If (Me.___CONSTRUCCIONDEOBRA Is Nothing) Then
                    Me.___CONSTRUCCIONDEOBRA = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.CONSTRUCCIONDEOBRA)( _
                        Me, _
                        "CONSTRUCCIONDEOBRA", _
                        New Global.System.String() {"AVANCEDEOBRA_CONSTRUCCIONDEOBRA"}, _
                        Function(e) Global.System.Object.Equals(e.Id, Me.AVANCEDEOBRA_CONSTRUCCIONDEOBRA), _
                        Function() Me._CONSTRUCCIONDEOBRA, _
                        Sub(e) Me._CONSTRUCCIONDEOBRA = e)
                End If
                Return Me.___CONSTRUCCIONDEOBRA
            End Get
        End Property
        
        Private ___CONSTRUCCIONDEOBRA As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.CONSTRUCCIONDEOBRA)
        
    End Class
    #End Region
    
    #Region "CONSTRUCCIONDEOBRA"
    <Global.System.Runtime.Serialization.DataContract(Namespace:="http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class CONSTRUCCIONDEOBRA
        Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation
        Private Sub OnOBRA_CONSTRUCCIONDEOBRAChanged()
            Me.___OnPropertyChanged("OBRA_CONSTRUCCIONDEOBRA")
            Me.___OnPropertyChanged("OBRA")
        End Sub
        
        Private Property _IdImplementation() As Integer Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.Id
            Get
                Return Me.Id
            End Get
            Set(ByVal value As Integer)
                Me.Id = value
            End Set
        End Property
        
        Private Sub OnIdChanged()
            Me.___OnPropertyChanged("Id")
        End Sub
        
        Private Property _CODIGOImplementation() As String Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.CODIGO
            Get
                Return Me.CODIGO
            End Get
            Set(ByVal value As String)
                Me.CODIGO = value
            End Set
        End Property
        
        Private Sub OnCODIGOChanged()
            Me.___OnPropertyChanged("CODIGO")
        End Sub
        
        Private Property _TIPOImplementation() As String Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.TIPO
            Get
                Return Me.TIPO
            End Get
            Set(ByVal value As String)
                Me.TIPO = value
            End Set
        End Property
        
        Private Sub OnTIPOChanged()
            Me.___OnPropertyChanged("TIPO")
        End Sub
        
        Private Property _FECHAImplementation() As Date Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.FECHA
            Get
                Return Me.FECHA
            End Get
            Set(ByVal value As Date)
                Me.FECHA = value
            End Set
        End Property
        
        Private Sub OnFECHAChanged()
            Me.___OnPropertyChanged("FECHA")
        End Sub
        
        Private ReadOnly Property _CreatedByImplementation() As String Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.CreatedBy
            Get
                Return Me.CreatedBy
            End Get
        End Property
        
        Private Sub OnCreatedByChanged()
            Me.___OnPropertyChanged("CreatedBy")
        End Sub
        
        Private ReadOnly Property _CreatedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.Created
            Get
                Return Me.Created
            End Get
        End Property
        
        Private Sub OnCreatedChanged()
            Me.___OnPropertyChanged("Created")
        End Sub
        
        Private ReadOnly Property _ModifiedByImplementation() As String Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.ModifiedBy
            Get
                Return Me.ModifiedBy
            End Get
        End Property
        
        Private Sub OnModifiedByChanged()
            Me.___OnPropertyChanged("ModifiedBy")
        End Sub
        
        Private ReadOnly Property _ModifiedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.Modified
            Get
                Return Me.Modified
            End Get
        End Property
        
        Private Sub OnModifiedChanged()
            Me.___OnPropertyChanged("Modified")
        End Sub
        
        Private Property _RowVersionImplementation() As Byte() Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.RowVersion
            Get
                Return Me.RowVersion
            End Get
            Set(ByVal value As Byte())
                Me.RowVersion = value
            End Set
        End Property
        
        Private Sub OnRowVersionChanged()
            Me.___OnPropertyChanged("RowVersion")
        End Sub
        
        Private Property _OBRAImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.OBRA
            Get
                Return Me.OBRA
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.OBRA = DirectCast(value, Global.LightSwitchApplication.Implementation.OBRA)
            End Set
        End Property
        
        Private ReadOnly Property __OBRA As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.OBRA) 
            Get
                If (Me.___OBRA Is Nothing) Then
                    Me.___OBRA = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.OBRA)( _
                        Me, _
                        "OBRA", _
                        New Global.System.String() {"OBRA_CONSTRUCCIONDEOBRA"}, _
                        Function(e) Global.System.Object.Equals(e.Id, Me.OBRA_CONSTRUCCIONDEOBRA), _
                        Function() Me._OBRA, _
                        Sub(e) Me._OBRA = e)
                End If
                Return Me.___OBRA
            End Get
        End Property
        
        Private ___OBRA As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.OBRA)
        
        Private ReadOnly Property _AVANCEDEOBRAsImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.CONSTRUCCIONDEOBRA.DetailsClass.IImplementation.AVANCEDEOBRAs
            Get
                Return Me.AVANCEDEOBRAs
            End Get
        End Property
        
        Friend ReadOnly Property __AVANCEDEOBRAs As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.AVANCEDEOBRA) 
            Get
                If (Me.___AVANCEDEOBRAs Is Nothing) Then
                    Me.___AVANCEDEOBRAs = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.AVANCEDEOBRA)( _
                        Me, _
                        "AVANCEDEOBRAs", _
                        Function() Me._AVANCEDEOBRAs, _
                        Function(e) Global.System.Object.Equals(e.AVANCEDEOBRA_CONSTRUCCIONDEOBRA, Me.Id))
                End If
                Return Me.___AVANCEDEOBRAs
            End Get
        End Property
        
        Private ___AVANCEDEOBRAs As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.AVANCEDEOBRA)
        
    End Class
    #End Region
    
    #Region "INSPECCIONMUNICIPAL"
    <Global.System.Runtime.Serialization.DataContract(Namespace:="http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class INSPECCIONMUNICIPAL
        Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation
        Private Sub OnINSPECCIONMUNICIPAL_OBRAChanged()
            Me.___OnPropertyChanged("INSPECCIONMUNICIPAL_OBRA")
            Me.___OnPropertyChanged("OBRA")
        End Sub
        
        Private Property _IdImplementation() As Integer Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation.Id
            Get
                Return Me.Id
            End Get
            Set(ByVal value As Integer)
                Me.Id = value
            End Set
        End Property
        
        Private Sub OnIdChanged()
            Me.___OnPropertyChanged("Id")
        End Sub
        
        Private Property _FECHAREALIZADAImplementation() As Date Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation.FECHAREALIZADA
            Get
                Return Me.FECHAREALIZADA
            End Get
            Set(ByVal value As Date)
                Me.FECHAREALIZADA = value
            End Set
        End Property
        
        Private Sub OnFECHAREALIZADAChanged()
            Me.___OnPropertyChanged("FECHAREALIZADA")
        End Sub
        
        Private Property _ESTADOImplementation() As String Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation.ESTADO
            Get
                Return Me.ESTADO
            End Get
            Set(ByVal value As String)
                Me.ESTADO = value
            End Set
        End Property
        
        Private Sub OnESTADOChanged()
            Me.___OnPropertyChanged("ESTADO")
        End Sub
        
        Private Property _FECHAESTADOImplementation() As Date Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation.FECHAESTADO
            Get
                Return Me.FECHAESTADO
            End Get
            Set(ByVal value As Date)
                Me.FECHAESTADO = value
            End Set
        End Property
        
        Private Sub OnFECHAESTADOChanged()
            Me.___OnPropertyChanged("FECHAESTADO")
        End Sub
        
        Private ReadOnly Property _CreatedByImplementation() As String Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation.CreatedBy
            Get
                Return Me.CreatedBy
            End Get
        End Property
        
        Private Sub OnCreatedByChanged()
            Me.___OnPropertyChanged("CreatedBy")
        End Sub
        
        Private ReadOnly Property _CreatedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation.Created
            Get
                Return Me.Created
            End Get
        End Property
        
        Private Sub OnCreatedChanged()
            Me.___OnPropertyChanged("Created")
        End Sub
        
        Private ReadOnly Property _ModifiedByImplementation() As String Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation.ModifiedBy
            Get
                Return Me.ModifiedBy
            End Get
        End Property
        
        Private Sub OnModifiedByChanged()
            Me.___OnPropertyChanged("ModifiedBy")
        End Sub
        
        Private ReadOnly Property _ModifiedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation.Modified
            Get
                Return Me.Modified
            End Get
        End Property
        
        Private Sub OnModifiedChanged()
            Me.___OnPropertyChanged("Modified")
        End Sub
        
        Private Property _RowVersionImplementation() As Byte() Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation.RowVersion
            Get
                Return Me.RowVersion
            End Get
            Set(ByVal value As Byte())
                Me.RowVersion = value
            End Set
        End Property
        
        Private Sub OnRowVersionChanged()
            Me.___OnPropertyChanged("RowVersion")
        End Sub
        
        Private Property _OBRAImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.INSPECCIONMUNICIPAL.DetailsClass.IImplementation.OBRA
            Get
                Return Me.OBRA
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.OBRA = DirectCast(value, Global.LightSwitchApplication.Implementation.OBRA)
            End Set
        End Property
        
        Private ReadOnly Property __OBRA As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.OBRA) 
            Get
                If (Me.___OBRA Is Nothing) Then
                    Me.___OBRA = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.OBRA)( _
                        Me, _
                        "OBRA", _
                        New Global.System.String() {"INSPECCIONMUNICIPAL_OBRA"}, _
                        Function(e) Global.System.Object.Equals(e.Id, Me.INSPECCIONMUNICIPAL_OBRA), _
                        Function() Me._OBRA, _
                        Sub(e) Me._OBRA = e)
                End If
                Return Me.___OBRA
            End Get
        End Property
        
        Private ___OBRA As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.OBRA)
        
    End Class
    #End Region
    
    #Region "INSPECCION"
    <Global.System.Runtime.Serialization.DataContract(Namespace:="http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class INSPECCION
        Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation
        Private Sub OnINSPECCION_OBRAChanged()
            Me.___OnPropertyChanged("INSPECCION_OBRA")
            Me.___OnPropertyChanged("OBRA")
        End Sub
        
        Private Property _IdImplementation() As Integer Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.Id
            Get
                Return Me.Id
            End Get
            Set(ByVal value As Integer)
                Me.Id = value
            End Set
        End Property
        
        Private Sub OnIdChanged()
            Me.___OnPropertyChanged("Id")
        End Sub
        
        Private Property _FECHAImplementation() As Date Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.FECHA
            Get
                Return Me.FECHA
            End Get
            Set(ByVal value As Date)
                Me.FECHA = value
            End Set
        End Property
        
        Private Sub OnFECHAChanged()
            Me.___OnPropertyChanged("FECHA")
        End Sub
        
        Private Property _CATEGORIAImplementation() As String Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.CATEGORIA
            Get
                Return Me.CATEGORIA
            End Get
            Set(ByVal value As String)
                Me.CATEGORIA = value
            End Set
        End Property
        
        Private Sub OnCATEGORIAChanged()
            Me.___OnPropertyChanged("CATEGORIA")
        End Sub
        
        Private Property _ESTADOImplementation() As String Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.ESTADO
            Get
                Return Me.ESTADO
            End Get
            Set(ByVal value As String)
                Me.ESTADO = value
            End Set
        End Property
        
        Private Sub OnESTADOChanged()
            Me.___OnPropertyChanged("ESTADO")
        End Sub
        
        Private Property _FECHADEESTADOImplementation() As Date Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.FECHADEESTADO
            Get
                Return Me.FECHADEESTADO
            End Get
            Set(ByVal value As Date)
                Me.FECHADEESTADO = value
            End Set
        End Property
        
        Private Sub OnFECHADEESTADOChanged()
            Me.___OnPropertyChanged("FECHADEESTADO")
        End Sub
        
        Private ReadOnly Property _CreatedByImplementation() As String Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.CreatedBy
            Get
                Return Me.CreatedBy
            End Get
        End Property
        
        Private Sub OnCreatedByChanged()
            Me.___OnPropertyChanged("CreatedBy")
        End Sub
        
        Private ReadOnly Property _CreatedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.Created
            Get
                Return Me.Created
            End Get
        End Property
        
        Private Sub OnCreatedChanged()
            Me.___OnPropertyChanged("Created")
        End Sub
        
        Private ReadOnly Property _ModifiedByImplementation() As String Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.ModifiedBy
            Get
                Return Me.ModifiedBy
            End Get
        End Property
        
        Private Sub OnModifiedByChanged()
            Me.___OnPropertyChanged("ModifiedBy")
        End Sub
        
        Private ReadOnly Property _ModifiedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.Modified
            Get
                Return Me.Modified
            End Get
        End Property
        
        Private Sub OnModifiedChanged()
            Me.___OnPropertyChanged("Modified")
        End Sub
        
        Private Property _RowVersionImplementation() As Byte() Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.RowVersion
            Get
                Return Me.RowVersion
            End Get
            Set(ByVal value As Byte())
                Me.RowVersion = value
            End Set
        End Property
        
        Private Sub OnRowVersionChanged()
            Me.___OnPropertyChanged("RowVersion")
        End Sub
        
        Private Property _OBRAImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.INSPECCION.DetailsClass.IImplementation.OBRA
            Get
                Return Me.OBRA
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.OBRA = DirectCast(value, Global.LightSwitchApplication.Implementation.OBRA)
            End Set
        End Property
        
        Private ReadOnly Property __OBRA As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.OBRA) 
            Get
                If (Me.___OBRA Is Nothing) Then
                    Me.___OBRA = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.OBRA)( _
                        Me, _
                        "OBRA", _
                        New Global.System.String() {"INSPECCION_OBRA"}, _
                        Function(e) Global.System.Object.Equals(e.Id, Me.INSPECCION_OBRA), _
                        Function() Me._OBRA, _
                        Sub(e) Me._OBRA = e)
                End If
                Return Me.___OBRA
            End Get
        End Property
        
        Private ___OBRA As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.OBRA)
        
    End Class
    #End Region
    
    #Region "OBRA"
    <Global.System.Runtime.Serialization.DataContract(Namespace:="http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class OBRA
        Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation
        Private Property _IdImplementation() As Integer Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.Id
            Get
                Return Me.Id
            End Get
            Set(ByVal value As Integer)
                Me.Id = value
            End Set
        End Property
        
        Private Sub OnIdChanged()
            Me.___OnPropertyChanged("Id")
        End Sub
        
        Private Property _CODIGOImplementation() As String Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.CODIGO
            Get
                Return Me.CODIGO
            End Get
            Set(ByVal value As String)
                Me.CODIGO = value
            End Set
        End Property
        
        Private Sub OnCODIGOChanged()
            Me.___OnPropertyChanged("CODIGO")
        End Sub
        
        Private Property _NOMBREImplementation() As String Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.NOMBRE
            Get
                Return Me.NOMBRE
            End Get
            Set(ByVal value As String)
                Me.NOMBRE = value
            End Set
        End Property
        
        Private Sub OnNOMBREChanged()
            Me.___OnPropertyChanged("NOMBRE")
        End Sub
        
        Private Property _SUPERFICIEENMETROSCUADRADOSImplementation() As Double Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.SUPERFICIEENMETROSCUADRADOS
            Get
                Return Me.SUPERFICIEENMETROSCUADRADOS
            End Get
            Set(ByVal value As Double)
                Me.SUPERFICIEENMETROSCUADRADOS = value
            End Set
        End Property
        
        Private Sub OnSUPERFICIEENMETROSCUADRADOSChanged()
            Me.___OnPropertyChanged("SUPERFICIEENMETROSCUADRADOS")
        End Sub
        
        Private Property _FECHAINICIOImplementation() As Date Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.FECHAINICIO
            Get
                Return Me.FECHAINICIO
            End Get
            Set(ByVal value As Date)
                Me.FECHAINICIO = value
            End Set
        End Property
        
        Private Sub OnFECHAINICIOChanged()
            Me.___OnPropertyChanged("FECHAINICIO")
        End Sub
        
        Private Property _FECHAPROBABLEFINImplementation() As Date Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.FECHAPROBABLEFIN
            Get
                Return Me.FECHAPROBABLEFIN
            End Get
            Set(ByVal value As Date)
                Me.FECHAPROBABLEFIN = value
            End Set
        End Property
        
        Private Sub OnFECHAPROBABLEFINChanged()
            Me.___OnPropertyChanged("FECHAPROBABLEFIN")
        End Sub
        
        Private ReadOnly Property _CreatedByImplementation() As String Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.CreatedBy
            Get
                Return Me.CreatedBy
            End Get
        End Property
        
        Private Sub OnCreatedByChanged()
            Me.___OnPropertyChanged("CreatedBy")
        End Sub
        
        Private ReadOnly Property _CreatedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.Created
            Get
                Return Me.Created
            End Get
        End Property
        
        Private Sub OnCreatedChanged()
            Me.___OnPropertyChanged("Created")
        End Sub
        
        Private ReadOnly Property _ModifiedByImplementation() As String Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.ModifiedBy
            Get
                Return Me.ModifiedBy
            End Get
        End Property
        
        Private Sub OnModifiedByChanged()
            Me.___OnPropertyChanged("ModifiedBy")
        End Sub
        
        Private ReadOnly Property _ModifiedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.Modified
            Get
                Return Me.Modified
            End Get
        End Property
        
        Private Sub OnModifiedChanged()
            Me.___OnPropertyChanged("Modified")
        End Sub
        
        Private Property _RowVersionImplementation() As Byte() Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.RowVersion
            Get
                Return Me.RowVersion
            End Get
            Set(ByVal value As Byte())
                Me.RowVersion = value
            End Set
        End Property
        
        Private Sub OnRowVersionChanged()
            Me.___OnPropertyChanged("RowVersion")
        End Sub
        
        Private ReadOnly Property _CONSTRUCCIONDEOBRAsImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.CONSTRUCCIONDEOBRAs
            Get
                Return Me.CONSTRUCCIONDEOBRAs
            End Get
        End Property
        
        Friend ReadOnly Property __CONSTRUCCIONDEOBRAs As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.CONSTRUCCIONDEOBRA) 
            Get
                If (Me.___CONSTRUCCIONDEOBRAs Is Nothing) Then
                    Me.___CONSTRUCCIONDEOBRAs = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.CONSTRUCCIONDEOBRA)( _
                        Me, _
                        "CONSTRUCCIONDEOBRAs", _
                        Function() Me._CONSTRUCCIONDEOBRAs, _
                        Function(e) Global.System.Object.Equals(e.OBRA_CONSTRUCCIONDEOBRA, Me.Id))
                End If
                Return Me.___CONSTRUCCIONDEOBRAs
            End Get
        End Property
        
        Private ___CONSTRUCCIONDEOBRAs As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.CONSTRUCCIONDEOBRA)
        
        Private ReadOnly Property _INSPECCIONsImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.INSPECCIONs
            Get
                Return Me.INSPECCIONs
            End Get
        End Property
        
        Friend ReadOnly Property __INSPECCIONs As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.INSPECCION) 
            Get
                If (Me.___INSPECCIONs Is Nothing) Then
                    Me.___INSPECCIONs = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.INSPECCION)( _
                        Me, _
                        "INSPECCIONs", _
                        Function() Me._INSPECCIONs, _
                        Function(e) Global.System.Object.Equals(e.INSPECCION_OBRA, Me.Id))
                End If
                Return Me.___INSPECCIONs
            End Get
        End Property
        
        Private ___INSPECCIONs As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.INSPECCION)
        
        Private ReadOnly Property _PLANOesImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.PLANOes
            Get
                Return Me.PLANOes
            End Get
        End Property
        
        Friend ReadOnly Property __PLANOes As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.PLANO) 
            Get
                If (Me.___PLANOes Is Nothing) Then
                    Me.___PLANOes = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.PLANO)( _
                        Me, _
                        "PLANOes", _
                        Function() Me._PLANOes, _
                        Function(e) Global.System.Object.Equals(e.PLANO_OBRA, Me.Id))
                End If
                Return Me.___PLANOes
            End Get
        End Property
        
        Private ___PLANOes As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.PLANO)
        
        Private ReadOnly Property _PERMISOSCollectionImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.PERMISOSCollection
            Get
                Return Me.PERMISOSCollection
            End Get
        End Property
        
        Friend ReadOnly Property __PERMISOSCollection As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.PERMISOS) 
            Get
                If (Me.___PERMISOSCollection Is Nothing) Then
                    Me.___PERMISOSCollection = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.PERMISOS)( _
                        Me, _
                        "PERMISOSCollection", _
                        Function() Me._PERMISOSCollection, _
                        Function(e) Global.System.Object.Equals(e.PERMISOS_OBRA, Me.Id))
                End If
                Return Me.___PERMISOSCollection
            End Get
        End Property
        
        Private ___PERMISOSCollection As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.PERMISOS)
        
        Private ReadOnly Property _INSPECCIONMUNICIPALsImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.OBRA.DetailsClass.IImplementation.INSPECCIONMUNICIPALs
            Get
                Return Me.INSPECCIONMUNICIPALs
            End Get
        End Property
        
        Friend ReadOnly Property __INSPECCIONMUNICIPALs As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.INSPECCIONMUNICIPAL) 
            Get
                If (Me.___INSPECCIONMUNICIPALs Is Nothing) Then
                    Me.___INSPECCIONMUNICIPALs = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.INSPECCIONMUNICIPAL)( _
                        Me, _
                        "INSPECCIONMUNICIPALs", _
                        Function() Me._INSPECCIONMUNICIPALs, _
                        Function(e) Global.System.Object.Equals(e.INSPECCIONMUNICIPAL_OBRA, Me.Id))
                End If
                Return Me.___INSPECCIONMUNICIPALs
            End Get
        End Property
        
        Private ___INSPECCIONMUNICIPALs As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.INSPECCIONMUNICIPAL)
        
    End Class
    #End Region
    
    #Region "PERMISOS"
    <Global.System.Runtime.Serialization.DataContract(Namespace:="http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class PERMISOS
        Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation
        Private Sub OnPERMISOS_OBRAChanged()
            Me.___OnPropertyChanged("PERMISOS_OBRA")
            Me.___OnPropertyChanged("OBRA")
        End Sub
        
        Private Property _IdImplementation() As Integer Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.Id
            Get
                Return Me.Id
            End Get
            Set(ByVal value As Integer)
                Me.Id = value
            End Set
        End Property
        
        Private Sub OnIdChanged()
            Me.___OnPropertyChanged("Id")
        End Sub
        
        Private Property _CODIGOImplementation() As String Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.CODIGO
            Get
                Return Me.CODIGO
            End Get
            Set(ByVal value As String)
                Me.CODIGO = value
            End Set
        End Property
        
        Private Sub OnCODIGOChanged()
            Me.___OnPropertyChanged("CODIGO")
        End Sub
        
        Private Property _NOMBREImplementation() As String Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.NOMBRE
            Get
                Return Me.NOMBRE
            End Get
            Set(ByVal value As String)
                Me.NOMBRE = value
            End Set
        End Property
        
        Private Sub OnNOMBREChanged()
            Me.___OnPropertyChanged("NOMBRE")
        End Sub
        
        Private Property _FECHADEPRESENTACIONImplementation() As Date Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.FECHADEPRESENTACION
            Get
                Return Me.FECHADEPRESENTACION
            End Get
            Set(ByVal value As Date)
                Me.FECHADEPRESENTACION = value
            End Set
        End Property
        
        Private Sub OnFECHADEPRESENTACIONChanged()
            Me.___OnPropertyChanged("FECHADEPRESENTACION")
        End Sub
        
        Private Property _FECHADEAPROBACIONImplementation() As Date Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.FECHADEAPROBACION
            Get
                Return Me.FECHADEAPROBACION
            End Get
            Set(ByVal value As Date)
                Me.FECHADEAPROBACION = value
            End Set
        End Property
        
        Private Sub OnFECHADEAPROBACIONChanged()
            Me.___OnPropertyChanged("FECHADEAPROBACION")
        End Sub
        
        Private ReadOnly Property _CreatedByImplementation() As String Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.CreatedBy
            Get
                Return Me.CreatedBy
            End Get
        End Property
        
        Private Sub OnCreatedByChanged()
            Me.___OnPropertyChanged("CreatedBy")
        End Sub
        
        Private ReadOnly Property _CreatedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.Created
            Get
                Return Me.Created
            End Get
        End Property
        
        Private Sub OnCreatedChanged()
            Me.___OnPropertyChanged("Created")
        End Sub
        
        Private ReadOnly Property _ModifiedByImplementation() As String Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.ModifiedBy
            Get
                Return Me.ModifiedBy
            End Get
        End Property
        
        Private Sub OnModifiedByChanged()
            Me.___OnPropertyChanged("ModifiedBy")
        End Sub
        
        Private ReadOnly Property _ModifiedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.Modified
            Get
                Return Me.Modified
            End Get
        End Property
        
        Private Sub OnModifiedChanged()
            Me.___OnPropertyChanged("Modified")
        End Sub
        
        Private Property _RowVersionImplementation() As Byte() Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.RowVersion
            Get
                Return Me.RowVersion
            End Get
            Set(ByVal value As Byte())
                Me.RowVersion = value
            End Set
        End Property
        
        Private Sub OnRowVersionChanged()
            Me.___OnPropertyChanged("RowVersion")
        End Sub
        
        Private Property _OBRAImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.PERMISOS.DetailsClass.IImplementation.OBRA
            Get
                Return Me.OBRA
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.OBRA = DirectCast(value, Global.LightSwitchApplication.Implementation.OBRA)
            End Set
        End Property
        
        Private ReadOnly Property __OBRA As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.OBRA) 
            Get
                If (Me.___OBRA Is Nothing) Then
                    Me.___OBRA = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.OBRA)( _
                        Me, _
                        "OBRA", _
                        New Global.System.String() {"PERMISOS_OBRA"}, _
                        Function(e) Global.System.Object.Equals(e.Id, Me.PERMISOS_OBRA), _
                        Function() Me._OBRA, _
                        Sub(e) Me._OBRA = e)
                End If
                Return Me.___OBRA
            End Get
        End Property
        
        Private ___OBRA As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.OBRA)
        
    End Class
    #End Region
    
    #Region "PLANO"
    <Global.System.Runtime.Serialization.DataContract(Namespace:="http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class PLANO
        Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation
        Private Sub OnPLANO_OBRAChanged()
            Me.___OnPropertyChanged("PLANO_OBRA")
            Me.___OnPropertyChanged("OBRA")
        End Sub
        
        Private Property _IdImplementation() As Integer Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.Id
            Get
                Return Me.Id
            End Get
            Set(ByVal value As Integer)
                Me.Id = value
            End Set
        End Property
        
        Private Sub OnIdChanged()
            Me.___OnPropertyChanged("Id")
        End Sub
        
        Private Property _NUMEROImplementation() As Integer Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.NUMERO
            Get
                Return Me.NUMERO
            End Get
            Set(ByVal value As Integer)
                Me.NUMERO = value
            End Set
        End Property
        
        Private Sub OnNUMEROChanged()
            Me.___OnPropertyChanged("NUMERO")
        End Sub
        
        Private Property _TIPOImplementation() As String Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.TIPO
            Get
                Return Me.TIPO
            End Get
            Set(ByVal value As String)
                Me.TIPO = value
            End Set
        End Property
        
        Private Sub OnTIPOChanged()
            Me.___OnPropertyChanged("TIPO")
        End Sub
        
        Private Property _FECHAREALIZADOImplementation() As Date Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.FECHAREALIZADO
            Get
                Return Me.FECHAREALIZADO
            End Get
            Set(ByVal value As Date)
                Me.FECHAREALIZADO = value
            End Set
        End Property
        
        Private Sub OnFECHAREALIZADOChanged()
            Me.___OnPropertyChanged("FECHAREALIZADO")
        End Sub
        
        Private Property _FECHAAPROBADOImplementation() As Date Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.FECHAAPROBADO
            Get
                Return Me.FECHAAPROBADO
            End Get
            Set(ByVal value As Date)
                Me.FECHAAPROBADO = value
            End Set
        End Property
        
        Private Sub OnFECHAAPROBADOChanged()
            Me.___OnPropertyChanged("FECHAAPROBADO")
        End Sub
        
        Private ReadOnly Property _CreatedByImplementation() As String Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.CreatedBy
            Get
                Return Me.CreatedBy
            End Get
        End Property
        
        Private Sub OnCreatedByChanged()
            Me.___OnPropertyChanged("CreatedBy")
        End Sub
        
        Private ReadOnly Property _CreatedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.Created
            Get
                Return Me.Created
            End Get
        End Property
        
        Private Sub OnCreatedChanged()
            Me.___OnPropertyChanged("Created")
        End Sub
        
        Private ReadOnly Property _ModifiedByImplementation() As String Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.ModifiedBy
            Get
                Return Me.ModifiedBy
            End Get
        End Property
        
        Private Sub OnModifiedByChanged()
            Me.___OnPropertyChanged("ModifiedBy")
        End Sub
        
        Private ReadOnly Property _ModifiedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.Modified
            Get
                Return Me.Modified
            End Get
        End Property
        
        Private Sub OnModifiedChanged()
            Me.___OnPropertyChanged("Modified")
        End Sub
        
        Private Property _RowVersionImplementation() As Byte() Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.RowVersion
            Get
                Return Me.RowVersion
            End Get
            Set(ByVal value As Byte())
                Me.RowVersion = value
            End Set
        End Property
        
        Private Sub OnRowVersionChanged()
            Me.___OnPropertyChanged("RowVersion")
        End Sub
        
        Private Property _OBRAImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.PLANO.DetailsClass.IImplementation.OBRA
            Get
                Return Me.OBRA
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.OBRA = DirectCast(value, Global.LightSwitchApplication.Implementation.OBRA)
            End Set
        End Property
        
        Private ReadOnly Property __OBRA As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.OBRA) 
            Get
                If (Me.___OBRA Is Nothing) Then
                    Me.___OBRA = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.OBRA)( _
                        Me, _
                        "OBRA", _
                        New Global.System.String() {"PLANO_OBRA"}, _
                        Function(e) Global.System.Object.Equals(e.Id, Me.PLANO_OBRA), _
                        Function() Me._OBRA, _
                        Sub(e) Me._OBRA = e)
                End If
                Return Me.___OBRA
            End Get
        End Property
        
        Private ___OBRA As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.OBRA)
        
    End Class
    #End Region
    
    #Region "ApplicationData"
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Partial Class ApplicationData
        Protected Overrides Function CreateEntityImplementation(Of T As Global.Microsoft.LightSwitch.IEntityObject)() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.AVANCEDEOBRA)) Then
                Return New Global.LightSwitchApplication.Implementation.AVANCEDEOBRA()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.CONSTRUCCIONDEOBRA)) Then
                Return New Global.LightSwitchApplication.Implementation.CONSTRUCCIONDEOBRA()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.INSPECCIONMUNICIPAL)) Then
                Return New Global.LightSwitchApplication.Implementation.INSPECCIONMUNICIPAL()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.INSPECCION)) Then
                Return New Global.LightSwitchApplication.Implementation.INSPECCION()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.OBRA)) Then
                Return New Global.LightSwitchApplication.Implementation.OBRA()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.PERMISOS)) Then
                Return New Global.LightSwitchApplication.Implementation.PERMISOS()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.PLANO)) Then
                Return New Global.LightSwitchApplication.Implementation.PLANO()
            End If
            Return Nothing
        End Function
    
        Protected Overrides Sub InitializeDataServiceContext()
            Me.Format.LoadServiceModel = AddressOf Global.LightSwitchApplication.Implementation.ApplicationData.GeneratedEdmModel.GetInstance
            Me.Format.UseJson()
        End Sub
    End Class
    #End Region
    
    #Region "DataServiceImplementationFactory"
    <Global.System.ComponentModel.Composition.PartCreationPolicy(Global.System.ComponentModel.Composition.CreationPolicy.Shared)> _
    <Global.System.ComponentModel.Composition.Export(GetType(Global.Microsoft.LightSwitch.Internal.IDataServiceFactory))> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class __DataServiceFactory
        Inherits Global.Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    
        Protected Overrides Function CreateDataService(ByVal dataServiceType As Global.System.Type) As Global.Microsoft.LightSwitch.IDataService
            If dataServiceType.Equals(GetType(Global.LightSwitchApplication.ApplicationData)) Then
                Return New Global.LightSwitchApplication.ApplicationData()
            End If
            Return MyBase.CreateDataService(dataServiceType)
        End Function
    
        Protected Overrides Function CreateDataServiceImplementation(Of TDataService As Global.Microsoft.LightSwitch.IDataService)(ByVal dataService As TDataService) As Global.Microsoft.LightSwitch.Internal.IDataServiceImplementation
            If GetType(TDataService).Equals(GetType(Global.LightSwitchApplication.ApplicationData)) Then
                Return New Global.LightSwitchApplication.Implementation.ApplicationData(Global.Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ApplicationData.svc"))
            End If
            Return MyBase.CreateDataServiceImplementation(dataService)
        End Function
    End Class
    #End Region
    
    <Global.System.ComponentModel.Composition.PartCreationPolicy(Global.System.ComponentModel.Composition.CreationPolicy.Shared)> _
    <Global.System.ComponentModel.Composition.Export(GetType(Global.Microsoft.LightSwitch.Internal.ITypeMappingProvider))> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class __TypeMapping
        Implements Global.Microsoft.LightSwitch.Internal.ITypeMappingProvider
        Private Function GetImplementationType(ByVal definitionType As Global.System.Type) As Global.System.Type Implements Global.Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType
            If GetType(Global.LightSwitchApplication.AVANCEDEOBRA).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.AVANCEDEOBRA)
            End If
            If GetType(Global.LightSwitchApplication.CONSTRUCCIONDEOBRA).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.CONSTRUCCIONDEOBRA)
            End If
            If GetType(Global.LightSwitchApplication.INSPECCIONMUNICIPAL).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.INSPECCIONMUNICIPAL)
            End If
            If GetType(Global.LightSwitchApplication.INSPECCION).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.INSPECCION)
            End If
            If GetType(Global.LightSwitchApplication.OBRA).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.OBRA)
            End If
            If GetType(Global.LightSwitchApplication.PERMISOS).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.PERMISOS)
            End If
            If GetType(Global.LightSwitchApplication.PLANO).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.PLANO)
            End If
            Return Nothing
        End Function
    End Class
End Namespace
