
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __PLANO = LightSwitchApplication.PLANO

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No hay ninguna descripción modelada
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
    Public NotInheritable Partial Class PLANO
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __PLANO, __PLANO.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Inicializa una nueva instancia de la entidad PLANO.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __PLANO))
            MyBase.New(entitySet)
            
            __PLANO.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PLANO_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PLANO_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return TryCast(Global.LightSwitchApplication.Application.Current, Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace))
            End Get
        End Property
        
        ''' <summary>
        ''' Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Id As Integer
            Get
                Return __PLANO.DetailsClass.GetValue(Me, __PLANO.DetailsClass.PropertySetProperties.Id)
            End Get
            Set
                __PLANO.DetailsClass.SetValue(Me, __PLANO.DetailsClass.PropertySetProperties.Id, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property NUMERO As Integer
            Get
                Return __PLANO.DetailsClass.GetValue(Me, __PLANO.DetailsClass.PropertySetProperties.NUMERO)
            End Get
            Set
                __PLANO.DetailsClass.SetValue(Me, __PLANO.DetailsClass.PropertySetProperties.NUMERO, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub NUMERO_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub NUMERO_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub NUMERO_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property TIPO As String
            Get
                Return __PLANO.DetailsClass.GetValue(Me, __PLANO.DetailsClass.PropertySetProperties.TIPO)
            End Get
            Set
                __PLANO.DetailsClass.SetValue(Me, __PLANO.DetailsClass.PropertySetProperties.TIPO, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub TIPO_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub TIPO_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub TIPO_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property FECHAREALIZADO As Date
            Get
                Return __PLANO.DetailsClass.GetValue(Me, __PLANO.DetailsClass.PropertySetProperties.FECHAREALIZADO)
            End Get
            Set
                __PLANO.DetailsClass.SetValue(Me, __PLANO.DetailsClass.PropertySetProperties.FECHAREALIZADO, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FECHAREALIZADO_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FECHAREALIZADO_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FECHAREALIZADO_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property FECHAAPROBADO As Date
            Get
                Return __PLANO.DetailsClass.GetValue(Me, __PLANO.DetailsClass.PropertySetProperties.FECHAAPROBADO)
            End Get
            Set
                __PLANO.DetailsClass.SetValue(Me, __PLANO.DetailsClass.PropertySetProperties.FECHAAPROBADO, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FECHAAPROBADO_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FECHAAPROBADO_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub FECHAAPROBADO_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property CreatedBy As String
            Get
                Return __PLANO.DetailsClass.GetValue(Me, __PLANO.DetailsClass.PropertySetProperties.CreatedBy)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreatedBy_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreatedBy_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreatedBy_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Created As Global.System.Nullable(Of Global.System.DateTimeOffset)
            Get
                Return __PLANO.DetailsClass.GetValue(Me, __PLANO.DetailsClass.PropertySetProperties.Created)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Created_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Created_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Created_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property ModifiedBy As String
            Get
                Return __PLANO.DetailsClass.GetValue(Me, __PLANO.DetailsClass.PropertySetProperties.ModifiedBy)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ModifiedBy_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ModifiedBy_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ModifiedBy_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Modified As Global.System.Nullable(Of Global.System.DateTimeOffset)
            Get
                Return __PLANO.DetailsClass.GetValue(Me, __PLANO.DetailsClass.PropertySetProperties.Modified)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Modified_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Modified_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Modified_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property RowVersion As Byte()
            Get
                Return __PLANO.DetailsClass.GetValue(Me, __PLANO.DetailsClass.PropertySetProperties.RowVersion)
            End Get
            Set
                __PLANO.DetailsClass.SetValue(Me, __PLANO.DetailsClass.PropertySetProperties.RowVersion, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property OBRA As Global.LightSwitchApplication.OBRA
            Get
                Return __PLANO.DetailsClass.GetValue(Me, __PLANO.DetailsClass.PropertySetProperties.OBRA)
            End Get
            Set
                __PLANO.DetailsClass.SetValue(Me, __PLANO.DetailsClass.PropertySetProperties.OBRA, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub OBRA_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub OBRA_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub OBRA_Changed()
        End Sub

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __PLANO, _
                __PLANO.DetailsClass, _
                __PLANO.DetailsClass.IImplementation, _
                __PLANO.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __PLANO, __PLANO.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __PLANO, __PLANO.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __PLANO.DetailsClass.PropertySetProperties.Id
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __PLANOEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __PLANO, __PLANO.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __PLANO, __PLANO.DetailsClass).Entry( _
                    AddressOf __PLANO.DetailsClass.__PLANO_CreateNew, _
                    AddressOf __PLANO.DetailsClass.__PLANO_Created, _
                    AddressOf __PLANO.DetailsClass.__PLANO_AllowSaveWithErrors)
            Private Shared Function __PLANO_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __PLANO)) As __PLANO
                Return New __PLANO(es)
            End Function
            Private Shared Sub __PLANO_Created(e As __PLANO)
                e.PLANO_Created()
            End Sub
            Private Shared Function __PLANO_AllowSaveWithErrors(e As __PLANO) As Boolean
                Dim result As Boolean = False
                e.PLANO_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __PLANO, __PLANO.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __PLANO, __PLANO.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __PLANO.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __PLANO, __PLANO.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__PLANO.DetailsClass.PropertySetProperties.Id),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property NUMERO As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__PLANO.DetailsClass.PropertySetProperties.NUMERO),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property TIPO As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__PLANO.DetailsClass.PropertySetProperties.TIPO),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property FECHAREALIZADO As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Date)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__PLANO.DetailsClass.PropertySetProperties.FECHAREALIZADO),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Date))
                    End Get
                End Property
                
                Public ReadOnly Property FECHAAPROBADO As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Date)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__PLANO.DetailsClass.PropertySetProperties.FECHAAPROBADO),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Date))
                    End Get
                End Property
                
                Public ReadOnly Property CreatedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__PLANO.DetailsClass.PropertySetProperties.CreatedBy),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Created As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__PLANO.DetailsClass.PropertySetProperties.Created),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)))
                    End Get
                End Property
                
                Public ReadOnly Property ModifiedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__PLANO.DetailsClass.PropertySetProperties.ModifiedBy),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Modified As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__PLANO.DetailsClass.PropertySetProperties.Modified),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)))
                    End Get
                End Property
                
                Public ReadOnly Property RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Byte())
                    Get
                        Return TryCast(
                            MyBase.GetItem(__PLANO.DetailsClass.PropertySetProperties.RowVersion),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Byte()))
                    End Get
                End Property
                
                Public ReadOnly Property OBRA As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __PLANO, __PLANO.DetailsClass, Global.LightSwitchApplication.OBRA)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__PLANO.DetailsClass.PropertySetProperties.OBRA),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __PLANO, __PLANO.DetailsClass, Global.LightSwitchApplication.OBRA))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property Id As Integer
                Shadows Property NUMERO As Integer
                Shadows Property TIPO As String
                Shadows Property FECHAREALIZADO As Date
                Shadows Property FECHAAPROBADO As Date
                Shadows ReadOnly Property CreatedBy As String
                Shadows ReadOnly Property Created As Global.System.Nullable(Of Global.System.DateTimeOffset)
                Shadows ReadOnly Property ModifiedBy As String
                Shadows ReadOnly Property Modified As Global.System.Nullable(Of Global.System.DateTimeOffset)
                Shadows Property RowVersion As Byte()
                Shadows Property OBRA As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Integer).Entry( _
                        "Id", _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._Id_Stub, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._Id_Validate, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._Id_GetImplementationValue, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._Id_SetImplementationValue, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._Id_OnValueChanged)
                Private Shared Sub _Id_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __PLANO.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Integer).Data), d As __PLANO.DetailsClass, sf As Object)
                    c(d, d._Id, sf)
                End Sub
                Private Shared Function _Id_ComputeIsReadOnly(e As __PLANO) As Boolean
                    Dim result As Boolean = False
                    e.Id_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Id_Validate(e As __PLANO, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Id_Validate(r)
                End Sub
                Private Shared Function _Id_GetImplementationValue(d As __PLANO.DetailsClass) As Integer
                    Return d.ImplementationEntity.Id
                End Function
                Private Shared Sub _Id_SetImplementationValue(d As __PLANO.DetailsClass, v As Integer)
                    d.ImplementationEntity.Id = v
                End Sub
                Private Shared Sub _Id_OnValueChanged(e As __PLANO)
                    e.Id_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly NUMERO As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Integer).Entry( _
                        "NUMERO", _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._NUMERO_Stub, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._NUMERO_ComputeIsReadOnly, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._NUMERO_Validate, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._NUMERO_GetImplementationValue, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._NUMERO_SetImplementationValue, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._NUMERO_OnValueChanged)
                Private Shared Sub _NUMERO_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __PLANO.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Integer).Data), d As __PLANO.DetailsClass, sf As Object)
                    c(d, d._NUMERO, sf)
                End Sub
                Private Shared Function _NUMERO_ComputeIsReadOnly(e As __PLANO) As Boolean
                    Dim result As Boolean = False
                    e.NUMERO_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _NUMERO_Validate(e As __PLANO, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.NUMERO_Validate(r)
                End Sub
                Private Shared Function _NUMERO_GetImplementationValue(d As __PLANO.DetailsClass) As Integer
                    Return d.ImplementationEntity.NUMERO
                End Function
                Private Shared Sub _NUMERO_SetImplementationValue(d As __PLANO.DetailsClass, v As Integer)
                    d.ImplementationEntity.NUMERO = v
                End Sub
                Private Shared Sub _NUMERO_OnValueChanged(e As __PLANO)
                    e.NUMERO_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly TIPO As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, String).Entry( _
                        "TIPO", _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._TIPO_Stub, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._TIPO_ComputeIsReadOnly, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._TIPO_Validate, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._TIPO_GetImplementationValue, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._TIPO_SetImplementationValue, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._TIPO_OnValueChanged)
                Private Shared Sub _TIPO_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __PLANO.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, String).Data), d As __PLANO.DetailsClass, sf As Object)
                    c(d, d._TIPO, sf)
                End Sub
                Private Shared Function _TIPO_ComputeIsReadOnly(e As __PLANO) As Boolean
                    Dim result As Boolean = False
                    e.TIPO_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _TIPO_Validate(e As __PLANO, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.TIPO_Validate(r)
                End Sub
                Private Shared Function _TIPO_GetImplementationValue(d As __PLANO.DetailsClass) As String
                    Return d.ImplementationEntity.TIPO
                End Function
                Private Shared Sub _TIPO_SetImplementationValue(d As __PLANO.DetailsClass, v As String)
                    d.ImplementationEntity.TIPO = v
                End Sub
                Private Shared Sub _TIPO_OnValueChanged(e As __PLANO)
                    e.TIPO_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly FECHAREALIZADO As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Date).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Date).Entry( _
                        "FECHAREALIZADO", _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._FECHAREALIZADO_Stub, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._FECHAREALIZADO_ComputeIsReadOnly, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._FECHAREALIZADO_Validate, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._FECHAREALIZADO_GetImplementationValue, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._FECHAREALIZADO_SetImplementationValue, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._FECHAREALIZADO_OnValueChanged)
                Private Shared Sub _FECHAREALIZADO_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __PLANO.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Date).Data), d As __PLANO.DetailsClass, sf As Object)
                    c(d, d._FECHAREALIZADO, sf)
                End Sub
                Private Shared Function _FECHAREALIZADO_ComputeIsReadOnly(e As __PLANO) As Boolean
                    Dim result As Boolean = False
                    e.FECHAREALIZADO_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _FECHAREALIZADO_Validate(e As __PLANO, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.FECHAREALIZADO_Validate(r)
                End Sub
                Private Shared Function _FECHAREALIZADO_GetImplementationValue(d As __PLANO.DetailsClass) As Date
                    Return d.ImplementationEntity.FECHAREALIZADO
                End Function
                Private Shared Sub _FECHAREALIZADO_SetImplementationValue(d As __PLANO.DetailsClass, v As Date)
                    d.ImplementationEntity.FECHAREALIZADO = __PLANO.DetailsClass.TruncateDate(v)
                End Sub
                Private Shared Sub _FECHAREALIZADO_OnValueChanged(e As __PLANO)
                    e.FECHAREALIZADO_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly FECHAAPROBADO As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Date).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Date).Entry( _
                        "FECHAAPROBADO", _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._FECHAAPROBADO_Stub, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._FECHAAPROBADO_ComputeIsReadOnly, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._FECHAAPROBADO_Validate, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._FECHAAPROBADO_GetImplementationValue, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._FECHAAPROBADO_SetImplementationValue, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._FECHAAPROBADO_OnValueChanged)
                Private Shared Sub _FECHAAPROBADO_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __PLANO.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Date).Data), d As __PLANO.DetailsClass, sf As Object)
                    c(d, d._FECHAAPROBADO, sf)
                End Sub
                Private Shared Function _FECHAAPROBADO_ComputeIsReadOnly(e As __PLANO) As Boolean
                    Dim result As Boolean = False
                    e.FECHAAPROBADO_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _FECHAAPROBADO_Validate(e As __PLANO, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.FECHAAPROBADO_Validate(r)
                End Sub
                Private Shared Function _FECHAAPROBADO_GetImplementationValue(d As __PLANO.DetailsClass) As Date
                    Return d.ImplementationEntity.FECHAAPROBADO
                End Function
                Private Shared Sub _FECHAAPROBADO_SetImplementationValue(d As __PLANO.DetailsClass, v As Date)
                    d.ImplementationEntity.FECHAAPROBADO = __PLANO.DetailsClass.TruncateDate(v)
                End Sub
                Private Shared Sub _FECHAAPROBADO_OnValueChanged(e As __PLANO)
                    e.FECHAAPROBADO_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CreatedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, String).Entry( _
                        "CreatedBy", _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._CreatedBy_Stub, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._CreatedBy_Validate, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue, _
                        Nothing, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged)
                Private Shared Sub _CreatedBy_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __PLANO.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, String).Data), d As __PLANO.DetailsClass, sf As Object)
                    c(d, d._CreatedBy, sf)
                End Sub
                Private Shared Function _CreatedBy_ComputeIsReadOnly(e As __PLANO) As Boolean
                    Dim result As Boolean = False
                    e.CreatedBy_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _CreatedBy_Validate(e As __PLANO, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.CreatedBy_Validate(r)
                End Sub
                Private Shared Function _CreatedBy_GetImplementationValue(d As __PLANO.DetailsClass) As String
                    Return d.ImplementationEntity.CreatedBy
                End Function
                Private Shared Sub _CreatedBy_OnValueChanged(e As __PLANO)
                    e.CreatedBy_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Created As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry( _
                        "Created", _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._Created_Stub, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._Created_Validate, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._Created_GetImplementationValue, _
                        Nothing, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._Created_OnValueChanged)
                Private Shared Sub _Created_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __PLANO.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data), d As __PLANO.DetailsClass, sf As Object)
                    c(d, d._Created, sf)
                End Sub
                Private Shared Function _Created_ComputeIsReadOnly(e As __PLANO) As Boolean
                    Dim result As Boolean = False
                    e.Created_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Created_Validate(e As __PLANO, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Created_Validate(r)
                End Sub
                Private Shared Function _Created_GetImplementationValue(d As __PLANO.DetailsClass) As Global.System.Nullable(Of Global.System.DateTimeOffset)
                    Return d.ImplementationEntity.Created
                End Function
                Private Shared Sub _Created_OnValueChanged(e As __PLANO)
                    e.Created_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ModifiedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, String).Entry( _
                        "ModifiedBy", _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._ModifiedBy_Stub, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._ModifiedBy_Validate, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue, _
                        Nothing, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged)
                Private Shared Sub _ModifiedBy_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __PLANO.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, String).Data), d As __PLANO.DetailsClass, sf As Object)
                    c(d, d._ModifiedBy, sf)
                End Sub
                Private Shared Function _ModifiedBy_ComputeIsReadOnly(e As __PLANO) As Boolean
                    Dim result As Boolean = False
                    e.ModifiedBy_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ModifiedBy_Validate(e As __PLANO, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ModifiedBy_Validate(r)
                End Sub
                Private Shared Function _ModifiedBy_GetImplementationValue(d As __PLANO.DetailsClass) As String
                    Return d.ImplementationEntity.ModifiedBy
                End Function
                Private Shared Sub _ModifiedBy_OnValueChanged(e As __PLANO)
                    e.ModifiedBy_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Modified As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry( _
                        "Modified", _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._Modified_Stub, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._Modified_Validate, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._Modified_GetImplementationValue, _
                        Nothing, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._Modified_OnValueChanged)
                Private Shared Sub _Modified_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __PLANO.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data), d As __PLANO.DetailsClass, sf As Object)
                    c(d, d._Modified, sf)
                End Sub
                Private Shared Function _Modified_ComputeIsReadOnly(e As __PLANO) As Boolean
                    Dim result As Boolean = False
                    e.Modified_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Modified_Validate(e As __PLANO, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Modified_Validate(r)
                End Sub
                Private Shared Function _Modified_GetImplementationValue(d As __PLANO.DetailsClass) As Global.System.Nullable(Of Global.System.DateTimeOffset)
                    Return d.ImplementationEntity.Modified
                End Function
                Private Shared Sub _Modified_OnValueChanged(e As __PLANO)
                    e.Modified_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Byte()).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Byte()).Entry( _
                        "RowVersion", _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._RowVersion_Stub, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._RowVersion_Validate, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged)
                Private Shared Sub _RowVersion_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __PLANO.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Byte()).Data), d As __PLANO.DetailsClass, sf As Object)
                    c(d, d._RowVersion, sf)
                End Sub
                Private Shared Function _RowVersion_ComputeIsReadOnly(e As __PLANO) As Boolean
                    Dim result As Boolean = False
                    e.RowVersion_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _RowVersion_Validate(e As __PLANO, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.RowVersion_Validate(r)
                End Sub
                Private Shared Function _RowVersion_GetImplementationValue(d As __PLANO.DetailsClass) As Byte()
                    Return d.ImplementationEntity.RowVersion
                End Function
                Private Shared Sub _RowVersion_SetImplementationValue(d As __PLANO.DetailsClass, v As Byte())
                    d.ImplementationEntity.RowVersion = v
                End Sub
                Private Shared Sub _RowVersion_OnValueChanged(e As __PLANO)
                    e.RowVersion_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly OBRA As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __PLANO, __PLANO.DetailsClass, Global.LightSwitchApplication.OBRA).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __PLANO, __PLANO.DetailsClass, Global.LightSwitchApplication.OBRA).Entry( _
                        "OBRA", _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._OBRA_Stub, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._OBRA_ComputeIsReadOnly, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._OBRA_Validate, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._OBRA_GetCoreImplementationValue, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._OBRA_GetImplementationValue, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._OBRA_SetImplementationValue, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._OBRA_Refresh, _
                        AddressOf __PLANO.DetailsClass.PropertySetProperties._OBRA_OnValueChanged)
                Private Shared Sub _OBRA_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __PLANO.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __PLANO, __PLANO.DetailsClass, Global.LightSwitchApplication.OBRA).Data), d As __PLANO.DetailsClass, sf As Object)
                    c(d, d._OBRA, sf)
                End Sub
                Private Shared Function _OBRA_ComputeIsReadOnly(e As __PLANO) As Boolean
                    Dim result As Boolean = False
                    e.OBRA_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _OBRA_Validate(e As __PLANO, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.OBRA_Validate(r)
                End Sub
                Private Shared Function _OBRA_GetCoreImplementationValue(d as __PLANO.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.OBRA
                End Function
                Private Shared Function _OBRA_GetImplementationValue(d as __PLANO.DetailsClass) As Global.LightSwitchApplication.OBRA
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.OBRA, Global.LightSwitchApplication.OBRA.DetailsClass)(__PLANO.DetailsClass.PropertySetProperties.OBRA, d._OBRA)
                End Function
                Private Shared Sub _OBRA_SetImplementationValue(d As __PLANO.DetailsClass, v As Global.LightSwitchApplication.OBRA)
                    d.SetImplementationValue(__PLANO.DetailsClass.PropertySetProperties.OBRA, d._OBRA, Sub(i, ev) i.OBRA = ev, v)
                End Sub
                Private Shared Sub _OBRA_Refresh(d As __PLANO.DetailsClass)
                    d.RefreshNavigationProperty(__PLANO.DetailsClass.PropertySetProperties.OBRA, d._OBRA)
                End Sub
                Private Shared Sub _OBRA_OnValueChanged(e As __PLANO)
                    e.OBRA_Changed()
                End Sub
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _NUMERO As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _TIPO As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _FECHAREALIZADO As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Date).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _FECHAAPROBADO As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Date).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CreatedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Created As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ModifiedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Modified As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __PLANO, __PLANO.DetailsClass, Byte()).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _OBRA As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __PLANO, __PLANO.DetailsClass, Global.LightSwitchApplication.OBRA).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
